/*
 * Public Directory API
 *
 * <p>Working draft of the Konexus Public User directory API.</p><p>This API will be used to allow citizens to create and manage their UserProfiles including contact information and notification preferences. UserProfiles are allowed to contain multiple Emails, Phones, and Locations.</p><p>Weather Notification subscriptions are currently missing from the specification.
 *
 * The version of the OpenAPI document: 4.0.5
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// AddPhoneCommand
    /// </summary>
    [DataContract(Name = "AddPhoneCommand")]
    public partial class AddPhoneCommand : IEquatable<AddPhoneCommand>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public ContactTargetType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddPhoneCommand" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddPhoneCommand() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddPhoneCommand" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="display">display.</param>
        /// <param name="value">value (required).</param>
        /// <param name="makePrimary">makePrimary (required).</param>
        /// <param name="mobilePhone">mobilePhone (required).</param>
        public AddPhoneCommand(ContactTargetType type = default(ContactTargetType), string display = default(string), string value = default(string), bool makePrimary = default(bool), bool mobilePhone = default(bool))
        {
            this.Type = type;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for AddPhoneCommand and cannot be null");
            }
            this.Value = value;
            this.MakePrimary = makePrimary;
            this.MobilePhone = mobilePhone;
            this.Display = display;
        }

        /// <summary>
        /// Gets or Sets Display
        /// </summary>
        [DataMember(Name = "display", EmitDefaultValue = true)]
        public string Display { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Gets or Sets MakePrimary
        /// </summary>
        [DataMember(Name = "makePrimary", IsRequired = true, EmitDefaultValue = true)]
        public bool MakePrimary { get; set; }

        /// <summary>
        /// Gets or Sets MobilePhone
        /// </summary>
        [DataMember(Name = "mobilePhone", IsRequired = true, EmitDefaultValue = true)]
        public bool MobilePhone { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddPhoneCommand {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Display: ").Append(Display).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  MakePrimary: ").Append(MakePrimary).Append("\n");
            sb.Append("  MobilePhone: ").Append(MobilePhone).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddPhoneCommand);
        }

        /// <summary>
        /// Returns true if AddPhoneCommand instances are equal
        /// </summary>
        /// <param name="input">Instance of AddPhoneCommand to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddPhoneCommand input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                ) && 
                (
                    this.Display == input.Display ||
                    (this.Display != null &&
                    this.Display.Equals(input.Display))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.MakePrimary == input.MakePrimary ||
                    this.MakePrimary.Equals(input.MakePrimary)
                ) && 
                (
                    this.MobilePhone == input.MobilePhone ||
                    this.MobilePhone.Equals(input.MobilePhone)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Type.GetHashCode();
                if (this.Display != null)
                {
                    hashCode = (hashCode * 59) + this.Display.GetHashCode();
                }
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.MakePrimary.GetHashCode();
                hashCode = (hashCode * 59) + this.MobilePhone.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Value (string) minLength
            if (this.Value != null && this.Value.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Value, length must be greater than 1.", new [] { "Value" });
            }

            yield break;
        }
    }

}
