/*
 * Public Directory API
 *
 * <p>Working draft of the Konexus Public User directory API.</p><p>This API will be used to allow citizens to create and manage their UserProfiles including contact information and notification preferences. UserProfiles are allowed to contain multiple Emails, Phones, and Locations.</p><p>Weather Notification subscriptions are currently missing from the specification.
 *
 * The version of the OpenAPI document: 4.0.5
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// AvailableLanguagesResponse
    /// </summary>
    [DataContract(Name = "AvailableLanguagesResponse")]
    public partial class AvailableLanguagesResponse : IEquatable<AvailableLanguagesResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AvailableLanguagesResponse" /> class.
        /// </summary>
        /// <param name="writtenLanguages">writtenLanguages.</param>
        /// <param name="spokenLanguages">spokenLanguages.</param>
        public AvailableLanguagesResponse(List<LanguageCode> writtenLanguages = default(List<LanguageCode>), List<LanguageCode> spokenLanguages = default(List<LanguageCode>))
        {
            this.WrittenLanguages = writtenLanguages;
            this.SpokenLanguages = spokenLanguages;
        }

        /// <summary>
        /// Gets or Sets WrittenLanguages
        /// </summary>
        [DataMember(Name = "writtenLanguages", EmitDefaultValue = true)]
        public List<LanguageCode> WrittenLanguages { get; set; }

        /// <summary>
        /// Gets or Sets SpokenLanguages
        /// </summary>
        [DataMember(Name = "spokenLanguages", EmitDefaultValue = true)]
        public List<LanguageCode> SpokenLanguages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AvailableLanguagesResponse {\n");
            sb.Append("  WrittenLanguages: ").Append(WrittenLanguages).Append("\n");
            sb.Append("  SpokenLanguages: ").Append(SpokenLanguages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AvailableLanguagesResponse);
        }

        /// <summary>
        /// Returns true if AvailableLanguagesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AvailableLanguagesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AvailableLanguagesResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.WrittenLanguages == input.WrittenLanguages ||
                    this.WrittenLanguages != null &&
                    input.WrittenLanguages != null &&
                    this.WrittenLanguages.SequenceEqual(input.WrittenLanguages)
                ) && 
                (
                    this.SpokenLanguages == input.SpokenLanguages ||
                    this.SpokenLanguages != null &&
                    input.SpokenLanguages != null &&
                    this.SpokenLanguages.SequenceEqual(input.SpokenLanguages)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WrittenLanguages != null)
                {
                    hashCode = (hashCode * 59) + this.WrittenLanguages.GetHashCode();
                }
                if (this.SpokenLanguages != null)
                {
                    hashCode = (hashCode * 59) + this.SpokenLanguages.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
