/*
 * Konexus Platform API - Directory
 *
 * <p>Working draft of the Konexus Platform API - Directory Module</p>
 *
 * The version of the OpenAPI document: 4.3.1
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// Defines ContactTargetType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ContactTargetType
    {
        /// <summary>
        /// Enum Personal for value: Personal
        /// </summary>
        [EnumMember(Value = "Personal")]
        Personal = 1,

        /// <summary>
        /// Enum Work for value: Work
        /// </summary>
        [EnumMember(Value = "Work")]
        Work = 2
    }

}
