/*
 * Public Directory API
 *
 * <p>Working draft of the Konexus Public User directory API.</p><p>This API will be used to allow citizens to create and manage their UserProfiles including contact information and notification preferences. UserProfiles are allowed to contain multiple Emails, Phones, and Locations.</p><p>Weather Notification subscriptions are currently missing from the specification.
 *
 * The version of the OpenAPI document: 4.2.0
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// CreateVerificationNonceCommand
    /// </summary>
    [DataContract(Name = "CreateVerificationNonceCommand")]
    public partial class CreateVerificationNonceCommand : IEquatable<CreateVerificationNonceCommand>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateVerificationNonceCommand" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateVerificationNonceCommand() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateVerificationNonceCommand" /> class.
        /// </summary>
        /// <param name="nonce">A nonce is a random string, uniquely generated by the client to allow the server to verify that a request has   never been made before and helps prevent spamming end users with too many verification requests through email. (required).</param>
        public CreateVerificationNonceCommand(string nonce = default(string))
        {
            // to ensure "nonce" is required (not null)
            if (nonce == null)
            {
                throw new ArgumentNullException("nonce is a required property for CreateVerificationNonceCommand and cannot be null");
            }
            this.Nonce = nonce;
        }

        /// <summary>
        /// A nonce is a random string, uniquely generated by the client to allow the server to verify that a request has   never been made before and helps prevent spamming end users with too many verification requests through email.
        /// </summary>
        /// <value>A nonce is a random string, uniquely generated by the client to allow the server to verify that a request has   never been made before and helps prevent spamming end users with too many verification requests through email.</value>
        [DataMember(Name = "nonce", IsRequired = true, EmitDefaultValue = true)]
        public string Nonce { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateVerificationNonceCommand {\n");
            sb.Append("  Nonce: ").Append(Nonce).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateVerificationNonceCommand);
        }

        /// <summary>
        /// Returns true if CreateVerificationNonceCommand instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateVerificationNonceCommand to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateVerificationNonceCommand input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Nonce == input.Nonce ||
                    (this.Nonce != null &&
                    this.Nonce.Equals(input.Nonce))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Nonce != null)
                {
                    hashCode = (hashCode * 59) + this.Nonce.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Nonce (string) minLength
            if (this.Nonce != null && this.Nonce.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Nonce, length must be greater than 1.", new [] { "Nonce" });
            }

            yield break;
        }
    }

}
