/*
 * Konexus Platform API - Directory
 *
 * <p>Working draft of the Konexus Platform API - Directory Module</p>
 *
 * The version of the OpenAPI document: 4.3.1
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// CreateLocationCommand
    /// </summary>
    [DataContract(Name = "CreateLocationCommand")]
    public partial class CreateLocationCommand : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public AddressType? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLocationCommand" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateLocationCommand() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLocationCommand" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="type">type.</param>
        /// <param name="streetAddress">The full street address component, which may  include house number, street name, P.O. box, and multi-line  extended street address information.  This attribute MAY  contain newlines..</param>
        /// <param name="locality">The city or locality component..</param>
        /// <param name="region">The state or region component..</param>
        /// <param name="postalCode">The zip code or postal code component..</param>
        /// <param name="country">The country name component.When specified, the value  MUST be in ISO 3166-1 \&quot;alpha-2\&quot; code format [ISO3166]; e.g.,  the United States and Sweden are \&quot;US\&quot; and \&quot;SE\&quot;, respectively..</param>
        /// <param name="latitude">latitude.</param>
        /// <param name="longitude">longitude.</param>
        public CreateLocationCommand(string name = default(string), AddressType? type = default(AddressType?), string streetAddress = default(string), string locality = default(string), string region = default(string), string postalCode = default(string), string country = default(string), double? latitude = default(double?), double? longitude = default(double?))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateLocationCommand and cannot be null");
            }
            this.Name = name;
            this.Type = type;
            this.StreetAddress = streetAddress;
            this.Locality = locality;
            this.Region = region;
            this.PostalCode = postalCode;
            this.Country = country;
            this.Latitude = latitude;
            this.Longitude = longitude;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The full street address component, which may  include house number, street name, P.O. box, and multi-line  extended street address information.  This attribute MAY  contain newlines.
        /// </summary>
        /// <value>The full street address component, which may  include house number, street name, P.O. box, and multi-line  extended street address information.  This attribute MAY  contain newlines.</value>
        [DataMember(Name = "streetAddress", EmitDefaultValue = true)]
        public string StreetAddress { get; set; }

        /// <summary>
        /// The city or locality component.
        /// </summary>
        /// <value>The city or locality component.</value>
        [DataMember(Name = "locality", EmitDefaultValue = true)]
        public string Locality { get; set; }

        /// <summary>
        /// The state or region component.
        /// </summary>
        /// <value>The state or region component.</value>
        [DataMember(Name = "region", EmitDefaultValue = true)]
        public string Region { get; set; }

        /// <summary>
        /// The zip code or postal code component.
        /// </summary>
        /// <value>The zip code or postal code component.</value>
        [DataMember(Name = "postalCode", EmitDefaultValue = true)]
        public string PostalCode { get; set; }

        /// <summary>
        /// The country name component.When specified, the value  MUST be in ISO 3166-1 \&quot;alpha-2\&quot; code format [ISO3166]; e.g.,  the United States and Sweden are \&quot;US\&quot; and \&quot;SE\&quot;, respectively.
        /// </summary>
        /// <value>The country name component.When specified, the value  MUST be in ISO 3166-1 \&quot;alpha-2\&quot; code format [ISO3166]; e.g.,  the United States and Sweden are \&quot;US\&quot; and \&quot;SE\&quot;, respectively.</value>
        [DataMember(Name = "country", EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [DataMember(Name = "latitude", EmitDefaultValue = true)]
        public double? Latitude { get; set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [DataMember(Name = "longitude", EmitDefaultValue = true)]
        public double? Longitude { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateLocationCommand {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  StreetAddress: ").Append(StreetAddress).Append("\n");
            sb.Append("  Locality: ").Append(Locality).Append("\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            yield break;
        }
    }

}
