/*
 * Public Directory API
 *
 * <p>Working draft of the Konexus Public User directory API.</p><p>This API will be used to allow citizens to create and manage their UserProfiles including contact information and notification preferences. UserProfiles are allowed to contain multiple Emails, Phones, and Locations.</p><p>Weather Notification subscriptions are currently missing from the specification.
 *
 * The version of the OpenAPI document: 4.2.0
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// CreateUserProfileCommand
    /// </summary>
    [DataContract(Name = "CreateUserProfileCommand")]
    public partial class CreateUserProfileCommand : IEquatable<CreateUserProfileCommand>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateUserProfileCommand" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateUserProfileCommand() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateUserProfileCommand" /> class.
        /// </summary>
        /// <param name="firstName">firstName (required).</param>
        /// <param name="lastName">lastName (required).</param>
        /// <param name="displayName">Allow the user to customize their display name separate from their First and Last names. If left empty, the DisplayName will be calculated by concatenating FirstName and LastName..</param>
        /// <param name="preferredWrittenLanguage">Indicates the user&#39;s preferred written language and is  generally used for selecting a localized user interface.  The  value indicates the set of natural languages that are preferred.  The format of the value is the same as the HTTP Accept-Language  header field (not including \&quot;Accept-Language:\&quot;) and is specified  in Section 5.3.5 of [RFC7231].  The intent of this value is to  enable cloud applications to perform matching of language tags  [RFC4647] to the user&#39;s language preferences, regardless of what  may be indicated by a user agent (which might be shared), or in an  interaction that does not involve a user (such as in a delegated  OAuth 2.0 [RFC6749] style interaction) where normal HTTP  Accept-Language header negotiation cannot take place..</param>
        /// <param name="preferredSpokenLanguage">Indicates the user&#39;s preferred poken language and is  generally used for selecting a localized user interface.  The  value indicates the set of natural languages that are preferred.  The format of the value is the same as the HTTP Accept-Language  header field (not including \&quot;Accept-Language:\&quot;) and is specified  in Section 5.3.5 of [RFC7231].  The intent of this value is to  enable cloud applications to perform matching of language tags  [RFC4647] to the user&#39;s language preferences, regardless of what  may be indicated by a user agent (which might be shared), or in an  interaction that does not involve a user (such as in a delegated  OAuth 2.0 [RFC6749] style interaction) where normal HTTP  Accept-Language header negotiation cannot take place..</param>
        /// <param name="locale">Used to indicate the User&#39;s default location for purposes of  localizing such items as currency, date time format, or numerical  representations.  A valid value is a language tag as defined in  [RFC5646].  Computer languages are explicitly excluded.    A language tag is a sequence of one or more case-insensitive  sub-tags, each separated by a hyphen character (\&quot;-\&quot;, %x2D).  For  backward compatibility, servers MAY accept tags separated by an  underscore character (\&quot;_\&quot;, %x5F).  In most cases, a language tag  consists of a primary language sub-tag that identifies a broad  family of related languages (e.g., \&quot;en\&quot; &#x3D; English) and that is  optionally followed by a series of sub-tags that refine or narrow  that language&#39;s range (e.g., \&quot;en-CA\&quot; &#x3D; the variety of English as  communicated in Canada).  Whitespace is not allowed within a  language tag.  Example tags include:    fr, en-US, es-419, az-Arab, x-pig-latin, man-Nkoo-GN    See [RFC5646] for further information..</param>
        /// <param name="timezone">The User&#39;s time zone, in IANA Time Zone database format [RFC6557],  also known as the \&quot;Olson\&quot; time zone database format [Olson-TZ]  (e.g., \&quot;America/Los_Angeles\&quot;)..</param>
        /// <param name="externalId">The User&#39;s external identifier, if any. This is a unique identifier..</param>
        /// <param name="emails">emails.</param>
        /// <param name="phones">phones.</param>
        /// <param name="locations">locations.</param>
        /// <param name="memberships">memberships.</param>
        public CreateUserProfileCommand(string firstName = default(string), string lastName = default(string), string displayName = default(string), string preferredWrittenLanguage = default(string), string preferredSpokenLanguage = default(string), string locale = default(string), string timezone = default(string), string externalId = default(string), List<CreateEmailCommand> emails = default(List<CreateEmailCommand>), List<CreatePhoneCommand> phones = default(List<CreatePhoneCommand>), List<CreateLocationCommand> locations = default(List<CreateLocationCommand>), List<CreateGroupMembership> memberships = default(List<CreateGroupMembership>))
        {
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new ArgumentNullException("firstName is a required property for CreateUserProfileCommand and cannot be null");
            }
            this.FirstName = firstName;
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new ArgumentNullException("lastName is a required property for CreateUserProfileCommand and cannot be null");
            }
            this.LastName = lastName;
            this.DisplayName = displayName;
            this.PreferredWrittenLanguage = preferredWrittenLanguage;
            this.PreferredSpokenLanguage = preferredSpokenLanguage;
            this.Locale = locale;
            this.Timezone = timezone;
            this.ExternalId = externalId;
            this.Emails = emails;
            this.Phones = phones;
            this.Locations = locations;
            this.Memberships = memberships;
        }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [DataMember(Name = "firstName", IsRequired = true, EmitDefaultValue = true)]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [DataMember(Name = "lastName", IsRequired = true, EmitDefaultValue = true)]
        public string LastName { get; set; }

        /// <summary>
        /// Allow the user to customize their display name separate from their First and Last names. If left empty, the DisplayName will be calculated by concatenating FirstName and LastName.
        /// </summary>
        /// <value>Allow the user to customize their display name separate from their First and Last names. If left empty, the DisplayName will be calculated by concatenating FirstName and LastName.</value>
        [DataMember(Name = "displayName", EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Indicates the user&#39;s preferred written language and is  generally used for selecting a localized user interface.  The  value indicates the set of natural languages that are preferred.  The format of the value is the same as the HTTP Accept-Language  header field (not including \&quot;Accept-Language:\&quot;) and is specified  in Section 5.3.5 of [RFC7231].  The intent of this value is to  enable cloud applications to perform matching of language tags  [RFC4647] to the user&#39;s language preferences, regardless of what  may be indicated by a user agent (which might be shared), or in an  interaction that does not involve a user (such as in a delegated  OAuth 2.0 [RFC6749] style interaction) where normal HTTP  Accept-Language header negotiation cannot take place.
        /// </summary>
        /// <value>Indicates the user&#39;s preferred written language and is  generally used for selecting a localized user interface.  The  value indicates the set of natural languages that are preferred.  The format of the value is the same as the HTTP Accept-Language  header field (not including \&quot;Accept-Language:\&quot;) and is specified  in Section 5.3.5 of [RFC7231].  The intent of this value is to  enable cloud applications to perform matching of language tags  [RFC4647] to the user&#39;s language preferences, regardless of what  may be indicated by a user agent (which might be shared), or in an  interaction that does not involve a user (such as in a delegated  OAuth 2.0 [RFC6749] style interaction) where normal HTTP  Accept-Language header negotiation cannot take place.</value>
        [DataMember(Name = "preferredWrittenLanguage", EmitDefaultValue = true)]
        public string PreferredWrittenLanguage { get; set; }

        /// <summary>
        /// Indicates the user&#39;s preferred poken language and is  generally used for selecting a localized user interface.  The  value indicates the set of natural languages that are preferred.  The format of the value is the same as the HTTP Accept-Language  header field (not including \&quot;Accept-Language:\&quot;) and is specified  in Section 5.3.5 of [RFC7231].  The intent of this value is to  enable cloud applications to perform matching of language tags  [RFC4647] to the user&#39;s language preferences, regardless of what  may be indicated by a user agent (which might be shared), or in an  interaction that does not involve a user (such as in a delegated  OAuth 2.0 [RFC6749] style interaction) where normal HTTP  Accept-Language header negotiation cannot take place.
        /// </summary>
        /// <value>Indicates the user&#39;s preferred poken language and is  generally used for selecting a localized user interface.  The  value indicates the set of natural languages that are preferred.  The format of the value is the same as the HTTP Accept-Language  header field (not including \&quot;Accept-Language:\&quot;) and is specified  in Section 5.3.5 of [RFC7231].  The intent of this value is to  enable cloud applications to perform matching of language tags  [RFC4647] to the user&#39;s language preferences, regardless of what  may be indicated by a user agent (which might be shared), or in an  interaction that does not involve a user (such as in a delegated  OAuth 2.0 [RFC6749] style interaction) where normal HTTP  Accept-Language header negotiation cannot take place.</value>
        [DataMember(Name = "preferredSpokenLanguage", EmitDefaultValue = true)]
        public string PreferredSpokenLanguage { get; set; }

        /// <summary>
        /// Used to indicate the User&#39;s default location for purposes of  localizing such items as currency, date time format, or numerical  representations.  A valid value is a language tag as defined in  [RFC5646].  Computer languages are explicitly excluded.    A language tag is a sequence of one or more case-insensitive  sub-tags, each separated by a hyphen character (\&quot;-\&quot;, %x2D).  For  backward compatibility, servers MAY accept tags separated by an  underscore character (\&quot;_\&quot;, %x5F).  In most cases, a language tag  consists of a primary language sub-tag that identifies a broad  family of related languages (e.g., \&quot;en\&quot; &#x3D; English) and that is  optionally followed by a series of sub-tags that refine or narrow  that language&#39;s range (e.g., \&quot;en-CA\&quot; &#x3D; the variety of English as  communicated in Canada).  Whitespace is not allowed within a  language tag.  Example tags include:    fr, en-US, es-419, az-Arab, x-pig-latin, man-Nkoo-GN    See [RFC5646] for further information.
        /// </summary>
        /// <value>Used to indicate the User&#39;s default location for purposes of  localizing such items as currency, date time format, or numerical  representations.  A valid value is a language tag as defined in  [RFC5646].  Computer languages are explicitly excluded.    A language tag is a sequence of one or more case-insensitive  sub-tags, each separated by a hyphen character (\&quot;-\&quot;, %x2D).  For  backward compatibility, servers MAY accept tags separated by an  underscore character (\&quot;_\&quot;, %x5F).  In most cases, a language tag  consists of a primary language sub-tag that identifies a broad  family of related languages (e.g., \&quot;en\&quot; &#x3D; English) and that is  optionally followed by a series of sub-tags that refine or narrow  that language&#39;s range (e.g., \&quot;en-CA\&quot; &#x3D; the variety of English as  communicated in Canada).  Whitespace is not allowed within a  language tag.  Example tags include:    fr, en-US, es-419, az-Arab, x-pig-latin, man-Nkoo-GN    See [RFC5646] for further information.</value>
        [DataMember(Name = "locale", EmitDefaultValue = true)]
        public string Locale { get; set; }

        /// <summary>
        /// The User&#39;s time zone, in IANA Time Zone database format [RFC6557],  also known as the \&quot;Olson\&quot; time zone database format [Olson-TZ]  (e.g., \&quot;America/Los_Angeles\&quot;).
        /// </summary>
        /// <value>The User&#39;s time zone, in IANA Time Zone database format [RFC6557],  also known as the \&quot;Olson\&quot; time zone database format [Olson-TZ]  (e.g., \&quot;America/Los_Angeles\&quot;).</value>
        [DataMember(Name = "timezone", EmitDefaultValue = true)]
        public string Timezone { get; set; }

        /// <summary>
        /// The User&#39;s external identifier, if any. This is a unique identifier.
        /// </summary>
        /// <value>The User&#39;s external identifier, if any. This is a unique identifier.</value>
        [DataMember(Name = "externalId", EmitDefaultValue = true)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Gets or Sets Emails
        /// </summary>
        [DataMember(Name = "emails", EmitDefaultValue = true)]
        public List<CreateEmailCommand> Emails { get; set; }

        /// <summary>
        /// Gets or Sets Phones
        /// </summary>
        [DataMember(Name = "phones", EmitDefaultValue = true)]
        public List<CreatePhoneCommand> Phones { get; set; }

        /// <summary>
        /// Gets or Sets Locations
        /// </summary>
        [DataMember(Name = "locations", EmitDefaultValue = true)]
        public List<CreateLocationCommand> Locations { get; set; }

        /// <summary>
        /// Gets or Sets Memberships
        /// </summary>
        [DataMember(Name = "memberships", EmitDefaultValue = true)]
        public List<CreateGroupMembership> Memberships { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateUserProfileCommand {\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  PreferredWrittenLanguage: ").Append(PreferredWrittenLanguage).Append("\n");
            sb.Append("  PreferredSpokenLanguage: ").Append(PreferredSpokenLanguage).Append("\n");
            sb.Append("  Locale: ").Append(Locale).Append("\n");
            sb.Append("  Timezone: ").Append(Timezone).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  Emails: ").Append(Emails).Append("\n");
            sb.Append("  Phones: ").Append(Phones).Append("\n");
            sb.Append("  Locations: ").Append(Locations).Append("\n");
            sb.Append("  Memberships: ").Append(Memberships).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateUserProfileCommand);
        }

        /// <summary>
        /// Returns true if CreateUserProfileCommand instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateUserProfileCommand to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateUserProfileCommand input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                ) && 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.PreferredWrittenLanguage == input.PreferredWrittenLanguage ||
                    (this.PreferredWrittenLanguage != null &&
                    this.PreferredWrittenLanguage.Equals(input.PreferredWrittenLanguage))
                ) && 
                (
                    this.PreferredSpokenLanguage == input.PreferredSpokenLanguage ||
                    (this.PreferredSpokenLanguage != null &&
                    this.PreferredSpokenLanguage.Equals(input.PreferredSpokenLanguage))
                ) && 
                (
                    this.Locale == input.Locale ||
                    (this.Locale != null &&
                    this.Locale.Equals(input.Locale))
                ) && 
                (
                    this.Timezone == input.Timezone ||
                    (this.Timezone != null &&
                    this.Timezone.Equals(input.Timezone))
                ) && 
                (
                    this.ExternalId == input.ExternalId ||
                    (this.ExternalId != null &&
                    this.ExternalId.Equals(input.ExternalId))
                ) && 
                (
                    this.Emails == input.Emails ||
                    this.Emails != null &&
                    input.Emails != null &&
                    this.Emails.SequenceEqual(input.Emails)
                ) && 
                (
                    this.Phones == input.Phones ||
                    this.Phones != null &&
                    input.Phones != null &&
                    this.Phones.SequenceEqual(input.Phones)
                ) && 
                (
                    this.Locations == input.Locations ||
                    this.Locations != null &&
                    input.Locations != null &&
                    this.Locations.SequenceEqual(input.Locations)
                ) && 
                (
                    this.Memberships == input.Memberships ||
                    this.Memberships != null &&
                    input.Memberships != null &&
                    this.Memberships.SequenceEqual(input.Memberships)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FirstName != null)
                {
                    hashCode = (hashCode * 59) + this.FirstName.GetHashCode();
                }
                if (this.LastName != null)
                {
                    hashCode = (hashCode * 59) + this.LastName.GetHashCode();
                }
                if (this.DisplayName != null)
                {
                    hashCode = (hashCode * 59) + this.DisplayName.GetHashCode();
                }
                if (this.PreferredWrittenLanguage != null)
                {
                    hashCode = (hashCode * 59) + this.PreferredWrittenLanguage.GetHashCode();
                }
                if (this.PreferredSpokenLanguage != null)
                {
                    hashCode = (hashCode * 59) + this.PreferredSpokenLanguage.GetHashCode();
                }
                if (this.Locale != null)
                {
                    hashCode = (hashCode * 59) + this.Locale.GetHashCode();
                }
                if (this.Timezone != null)
                {
                    hashCode = (hashCode * 59) + this.Timezone.GetHashCode();
                }
                if (this.ExternalId != null)
                {
                    hashCode = (hashCode * 59) + this.ExternalId.GetHashCode();
                }
                if (this.Emails != null)
                {
                    hashCode = (hashCode * 59) + this.Emails.GetHashCode();
                }
                if (this.Phones != null)
                {
                    hashCode = (hashCode * 59) + this.Phones.GetHashCode();
                }
                if (this.Locations != null)
                {
                    hashCode = (hashCode * 59) + this.Locations.GetHashCode();
                }
                if (this.Memberships != null)
                {
                    hashCode = (hashCode * 59) + this.Memberships.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // FirstName (string) minLength
            if (this.FirstName != null && this.FirstName.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for FirstName, length must be greater than 1.", new [] { "FirstName" });
            }

            // LastName (string) minLength
            if (this.LastName != null && this.LastName.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LastName, length must be greater than 1.", new [] { "LastName" });
            }

            yield break;
        }
    }

}
