/*
 * Konexus Platform API - Directory
 *
 * <p>Working draft of the Konexus Platform API - Directory Module</p>
 *
 * The version of the OpenAPI document: 4.3.1
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// EmailAddress
    /// </summary>
    [DataContract(Name = "EmailAddress")]
    public partial class EmailAddress : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public ContactTargetType? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailAddress" /> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="primary">A Boolean value indicating the &#39;primary&#39; or preferred attribute  value for this attribute, e.g., the preferred mailing address or  the primary email address.The primary attribute value \&quot;true\&quot;  MUST appear no more than once.If not specified, the value of  \&quot;primary\&quot; SHALL be assumed to be \&quot;false\&quot;..</param>
        /// <param name="value">The attribute&#39;s significant value, e.g., email address, phone  number..</param>
        /// <param name="verification">verification.</param>
        public EmailAddress(ContactTargetType? type = default(ContactTargetType?), bool primary = default(bool), string value = default(string), VerificationStatus verification = default(VerificationStatus))
        {
            this.Type = type;
            this.Primary = primary;
            this.Value = value;
            this.Verification = verification;
        }

        /// <summary>
        /// A Boolean value indicating the &#39;primary&#39; or preferred attribute  value for this attribute, e.g., the preferred mailing address or  the primary email address.The primary attribute value \&quot;true\&quot;  MUST appear no more than once.If not specified, the value of  \&quot;primary\&quot; SHALL be assumed to be \&quot;false\&quot;.
        /// </summary>
        /// <value>A Boolean value indicating the &#39;primary&#39; or preferred attribute  value for this attribute, e.g., the preferred mailing address or  the primary email address.The primary attribute value \&quot;true\&quot;  MUST appear no more than once.If not specified, the value of  \&quot;primary\&quot; SHALL be assumed to be \&quot;false\&quot;.</value>
        [DataMember(Name = "primary", EmitDefaultValue = true)]
        public bool Primary { get; set; }

        /// <summary>
        /// A human-readable name, primarily used for display purposes and  having a mutability of \&quot;immutable\&quot;.
        /// </summary>
        /// <value>A human-readable name, primarily used for display purposes and  having a mutability of \&quot;immutable\&quot;.</value>
        [DataMember(Name = "display", EmitDefaultValue = true)]
        public string Display { get; private set; }

        /// <summary>
        /// Returns false as Display should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDisplay()
        {
            return false;
        }
        /// <summary>
        /// The attribute&#39;s significant value, e.g., email address, phone  number.
        /// </summary>
        /// <value>The attribute&#39;s significant value, e.g., email address, phone  number.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Gets or Sets Verification
        /// </summary>
        [DataMember(Name = "verification", EmitDefaultValue = false)]
        public VerificationStatus Verification { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailAddress {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Primary: ").Append(Primary).Append("\n");
            sb.Append("  Display: ").Append(Display).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Verification: ").Append(Verification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
