/*
 * Konexus Platform API - Directory
 *
 * <p>Working draft of the Konexus Platform API - Directory Module</p>
 *
 * The version of the OpenAPI document: 4.2.3
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// NotificationPreferences
    /// </summary>
    [DataContract(Name = "NotificationPreferences")]
    public partial class NotificationPreferences : IEquatable<NotificationPreferences>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationPreferences" /> class.
        /// </summary>
        /// <param name="locations">locations.</param>
        /// <param name="memberships">memberships.</param>
        /// <param name="preferredWrittenLanguage">Indicates the user&#39;s preferred written or spoken languages and is  generally used for selecting a localized user interface.  The  value indicates the set of natural languages that are preferred.  The format of the value is the same as the HTTP Accept-Language  header field (not including \&quot;Accept-Language:\&quot;) and is specified  in Section 5.3.5 of [RFC7231].  The intent of this value is to  enable cloud applications to perform matching of language tags  [RFC4647] to the user&#39;s language preferences, regardless of what  may be indicated by a user agent (which might be shared), or in an  interaction that does not involve a user (such as in a delegated  OAuth 2.0 [RFC6749] style interaction) where normal HTTP  Accept-Language header negotiation cannot take place..</param>
        /// <param name="preferredSpokenLanguage">preferredSpokenLanguage.</param>
        /// <param name="locale">Used to indicate the User&#39;s default location for purposes of  localizing such items as currency, date time format, or numerical  representations.  A valid value is a language tag as defined in  [RFC5646].  Computer languages are explicitly excluded.    A language tag is a sequence of one or more case-insensitive  sub-tags, each separated by a hyphen character (\&quot;-\&quot;, %x2D).  For  backward compatibility, servers MAY accept tags separated by an  underscore character (\&quot;_\&quot;, %x5F).  In most cases, a language tag  consists of a primary language sub-tag that identifies a broad  family of related languages (e.g., \&quot;en\&quot; &#x3D; English) and that is  optionally followed by a series of sub-tags that refine or narrow  that language&#39;s range (e.g., \&quot;en-CA\&quot; &#x3D; the variety of English as  communicated in Canada).  Whitespace is not allowed within a  language tag.  Example tags include:    fr, en-US, es-419, az-Arab, x-pig-latin, man-Nkoo-GN    See [RFC5646] for further information..</param>
        /// <param name="timezone">The User&#39;s time zone, in IANA Time Zone database format [RFC6557],  also known as the \&quot;Olson\&quot; time zone database format [Olson-TZ]  (e.g., \&quot;America/Los_Angeles\&quot;)..</param>
        public NotificationPreferences(LocationCollection locations = default(LocationCollection), GroupMemberships memberships = default(GroupMemberships), string preferredWrittenLanguage = default(string), string preferredSpokenLanguage = default(string), string locale = default(string), string timezone = default(string))
        {
            this.Locations = locations;
            this.Memberships = memberships;
            this.PreferredWrittenLanguage = preferredWrittenLanguage;
            this.PreferredSpokenLanguage = preferredSpokenLanguage;
            this.Locale = locale;
            this.Timezone = timezone;
        }

        /// <summary>
        /// Gets or Sets Locations
        /// </summary>
        [DataMember(Name = "locations", EmitDefaultValue = false)]
        public LocationCollection Locations { get; set; }

        /// <summary>
        /// Gets or Sets Memberships
        /// </summary>
        [DataMember(Name = "memberships", EmitDefaultValue = false)]
        public GroupMemberships Memberships { get; set; }

        /// <summary>
        /// Indicates the user&#39;s preferred written or spoken languages and is  generally used for selecting a localized user interface.  The  value indicates the set of natural languages that are preferred.  The format of the value is the same as the HTTP Accept-Language  header field (not including \&quot;Accept-Language:\&quot;) and is specified  in Section 5.3.5 of [RFC7231].  The intent of this value is to  enable cloud applications to perform matching of language tags  [RFC4647] to the user&#39;s language preferences, regardless of what  may be indicated by a user agent (which might be shared), or in an  interaction that does not involve a user (such as in a delegated  OAuth 2.0 [RFC6749] style interaction) where normal HTTP  Accept-Language header negotiation cannot take place.
        /// </summary>
        /// <value>Indicates the user&#39;s preferred written or spoken languages and is  generally used for selecting a localized user interface.  The  value indicates the set of natural languages that are preferred.  The format of the value is the same as the HTTP Accept-Language  header field (not including \&quot;Accept-Language:\&quot;) and is specified  in Section 5.3.5 of [RFC7231].  The intent of this value is to  enable cloud applications to perform matching of language tags  [RFC4647] to the user&#39;s language preferences, regardless of what  may be indicated by a user agent (which might be shared), or in an  interaction that does not involve a user (such as in a delegated  OAuth 2.0 [RFC6749] style interaction) where normal HTTP  Accept-Language header negotiation cannot take place.</value>
        [DataMember(Name = "preferredWrittenLanguage", EmitDefaultValue = true)]
        public string PreferredWrittenLanguage { get; set; }

        /// <summary>
        /// Gets or Sets PreferredSpokenLanguage
        /// </summary>
        [DataMember(Name = "preferredSpokenLanguage", EmitDefaultValue = true)]
        public string PreferredSpokenLanguage { get; set; }

        /// <summary>
        /// Used to indicate the User&#39;s default location for purposes of  localizing such items as currency, date time format, or numerical  representations.  A valid value is a language tag as defined in  [RFC5646].  Computer languages are explicitly excluded.    A language tag is a sequence of one or more case-insensitive  sub-tags, each separated by a hyphen character (\&quot;-\&quot;, %x2D).  For  backward compatibility, servers MAY accept tags separated by an  underscore character (\&quot;_\&quot;, %x5F).  In most cases, a language tag  consists of a primary language sub-tag that identifies a broad  family of related languages (e.g., \&quot;en\&quot; &#x3D; English) and that is  optionally followed by a series of sub-tags that refine or narrow  that language&#39;s range (e.g., \&quot;en-CA\&quot; &#x3D; the variety of English as  communicated in Canada).  Whitespace is not allowed within a  language tag.  Example tags include:    fr, en-US, es-419, az-Arab, x-pig-latin, man-Nkoo-GN    See [RFC5646] for further information.
        /// </summary>
        /// <value>Used to indicate the User&#39;s default location for purposes of  localizing such items as currency, date time format, or numerical  representations.  A valid value is a language tag as defined in  [RFC5646].  Computer languages are explicitly excluded.    A language tag is a sequence of one or more case-insensitive  sub-tags, each separated by a hyphen character (\&quot;-\&quot;, %x2D).  For  backward compatibility, servers MAY accept tags separated by an  underscore character (\&quot;_\&quot;, %x5F).  In most cases, a language tag  consists of a primary language sub-tag that identifies a broad  family of related languages (e.g., \&quot;en\&quot; &#x3D; English) and that is  optionally followed by a series of sub-tags that refine or narrow  that language&#39;s range (e.g., \&quot;en-CA\&quot; &#x3D; the variety of English as  communicated in Canada).  Whitespace is not allowed within a  language tag.  Example tags include:    fr, en-US, es-419, az-Arab, x-pig-latin, man-Nkoo-GN    See [RFC5646] for further information.</value>
        [DataMember(Name = "locale", EmitDefaultValue = true)]
        public string Locale { get; set; }

        /// <summary>
        /// The User&#39;s time zone, in IANA Time Zone database format [RFC6557],  also known as the \&quot;Olson\&quot; time zone database format [Olson-TZ]  (e.g., \&quot;America/Los_Angeles\&quot;).
        /// </summary>
        /// <value>The User&#39;s time zone, in IANA Time Zone database format [RFC6557],  also known as the \&quot;Olson\&quot; time zone database format [Olson-TZ]  (e.g., \&quot;America/Los_Angeles\&quot;).</value>
        [DataMember(Name = "timezone", EmitDefaultValue = true)]
        public string Timezone { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NotificationPreferences {\n");
            sb.Append("  Locations: ").Append(Locations).Append("\n");
            sb.Append("  Memberships: ").Append(Memberships).Append("\n");
            sb.Append("  PreferredWrittenLanguage: ").Append(PreferredWrittenLanguage).Append("\n");
            sb.Append("  PreferredSpokenLanguage: ").Append(PreferredSpokenLanguage).Append("\n");
            sb.Append("  Locale: ").Append(Locale).Append("\n");
            sb.Append("  Timezone: ").Append(Timezone).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NotificationPreferences);
        }

        /// <summary>
        /// Returns true if NotificationPreferences instances are equal
        /// </summary>
        /// <param name="input">Instance of NotificationPreferences to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NotificationPreferences input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Locations == input.Locations ||
                    (this.Locations != null &&
                    this.Locations.Equals(input.Locations))
                ) && 
                (
                    this.Memberships == input.Memberships ||
                    (this.Memberships != null &&
                    this.Memberships.Equals(input.Memberships))
                ) && 
                (
                    this.PreferredWrittenLanguage == input.PreferredWrittenLanguage ||
                    (this.PreferredWrittenLanguage != null &&
                    this.PreferredWrittenLanguage.Equals(input.PreferredWrittenLanguage))
                ) && 
                (
                    this.PreferredSpokenLanguage == input.PreferredSpokenLanguage ||
                    (this.PreferredSpokenLanguage != null &&
                    this.PreferredSpokenLanguage.Equals(input.PreferredSpokenLanguage))
                ) && 
                (
                    this.Locale == input.Locale ||
                    (this.Locale != null &&
                    this.Locale.Equals(input.Locale))
                ) && 
                (
                    this.Timezone == input.Timezone ||
                    (this.Timezone != null &&
                    this.Timezone.Equals(input.Timezone))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Locations != null)
                {
                    hashCode = (hashCode * 59) + this.Locations.GetHashCode();
                }
                if (this.Memberships != null)
                {
                    hashCode = (hashCode * 59) + this.Memberships.GetHashCode();
                }
                if (this.PreferredWrittenLanguage != null)
                {
                    hashCode = (hashCode * 59) + this.PreferredWrittenLanguage.GetHashCode();
                }
                if (this.PreferredSpokenLanguage != null)
                {
                    hashCode = (hashCode * 59) + this.PreferredSpokenLanguage.GetHashCode();
                }
                if (this.Locale != null)
                {
                    hashCode = (hashCode * 59) + this.Locale.GetHashCode();
                }
                if (this.Timezone != null)
                {
                    hashCode = (hashCode * 59) + this.Timezone.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
