/*
 * Konexus Platform API - Directory
 *
 * <p>Working draft of the Konexus Platform API - Directory Module</p>
 *
 * The version of the OpenAPI document: 4.3.0
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// SendVerificationCommand
    /// </summary>
    [DataContract(Name = "SendVerificationCommand")]
    public partial class SendVerificationCommand : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendVerificationCommand" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendVerificationCommand() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendVerificationCommand" /> class.
        /// </summary>
        /// <param name="verificationNonce">Verification Nonce is reserved by the client in a previous command to prevent spamming end users with too many   responses within a reasonable timeframe enforced by the server. (required).</param>
        public SendVerificationCommand(string verificationNonce = default(string))
        {
            // to ensure "verificationNonce" is required (not null)
            if (verificationNonce == null)
            {
                throw new ArgumentNullException("verificationNonce is a required property for SendVerificationCommand and cannot be null");
            }
            this.VerificationNonce = verificationNonce;
        }

        /// <summary>
        /// Verification Nonce is reserved by the client in a previous command to prevent spamming end users with too many   responses within a reasonable timeframe enforced by the server.
        /// </summary>
        /// <value>Verification Nonce is reserved by the client in a previous command to prevent spamming end users with too many   responses within a reasonable timeframe enforced by the server.</value>
        [DataMember(Name = "verificationNonce", IsRequired = true, EmitDefaultValue = true)]
        public string VerificationNonce { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendVerificationCommand {\n");
            sb.Append("  VerificationNonce: ").Append(VerificationNonce).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // VerificationNonce (string) minLength
            if (this.VerificationNonce != null && this.VerificationNonce.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for VerificationNonce, length must be greater than 1.", new [] { "VerificationNonce" });
            }

            yield break;
        }
    }

}
