/*
 * Konexus Platform API - Directory
 *
 * <p>Working draft of the Konexus Platform API - Directory Module</p>
 *
 * The version of the OpenAPI document: 4.3.1
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// TimeZoneSummary
    /// </summary>
    [DataContract(Name = "TimeZoneSummary")]
    public partial class TimeZoneSummary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TimeZoneSummary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public TimeZoneSummary()
        {
        }

        /// <summary>
        /// The display name of the time zone&#39;s standard time.
        /// </summary>
        /// <value>The display name of the time zone&#39;s standard time.</value>
        [DataMember(Name = "standardName", EmitDefaultValue = true)]
        public string StandardName { get; private set; }

        /// <summary>
        /// Returns false as StandardName should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeStandardName()
        {
            return false;
        }
        /// <summary>
        /// The time zone identifier.
        /// </summary>
        /// <value>The time zone identifier.</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; private set; }

        /// <summary>
        /// Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return false;
        }
        /// <summary>
        /// The time zone&#39;s general display name.
        /// </summary>
        /// <value>The time zone&#39;s general display name.</value>
        [DataMember(Name = "displayName", EmitDefaultValue = true)]
        public string DisplayName { get; private set; }

        /// <summary>
        /// Returns false as DisplayName should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDisplayName()
        {
            return false;
        }
        /// <summary>
        /// Gets the display name for the current time zone&#39;s daylight saving time.
        /// </summary>
        /// <value>Gets the display name for the current time zone&#39;s daylight saving time.</value>
        [DataMember(Name = "daylightName", EmitDefaultValue = true)]
        public string DaylightName { get; private set; }

        /// <summary>
        /// Returns false as DaylightName should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDaylightName()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets BaseUtcOffset
        /// </summary>
        [DataMember(Name = "baseUtcOffset", EmitDefaultValue = false)]
        public string BaseUtcOffset { get; private set; }

        /// <summary>
        /// Returns false as BaseUtcOffset should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBaseUtcOffset()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TimeZoneSummary {\n");
            sb.Append("  StandardName: ").Append(StandardName).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  DaylightName: ").Append(DaylightName).Append("\n");
            sb.Append("  BaseUtcOffset: ").Append(BaseUtcOffset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
