/*
 * Public Directory API
 *
 * <p>Working draft of the Konexus Public User directory API.</p><p>This API will be used to allow citizens to create and manage their UserProfiles including contact information and notification preferences. UserProfiles are allowed to contain multiple Emails, Phones, and Locations.</p><p>Weather Notification subscriptions are currently missing from the specification.
 *
 * The version of the OpenAPI document: 4.2.0
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// UserProfile
    /// </summary>
    [DataContract(Name = "UserProfile")]
    public partial class UserProfile : IEquatable<UserProfile>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserProfile" /> class.
        /// </summary>
        /// <param name="tenantId">Identifier for the Tenant this resource belongs to..</param>
        /// <param name="directories">The set of Directory Tags this resource belongs to. A UserProfile may belong to multiple directories..</param>
        /// <param name="id">A unique identifier for a SCIM resource as defined by the service  provider. Each representation of the resource MUST include a  non-empty \&quot;id\&quot; value.This identifier MUST be unique across the  SCIM service provider&#39;s entire set of resources. It MUST be a  stable, non-reassignable identifier that does not change when the  same resource is returned in subsequent requests.The value of  the \&quot;id\&quot; attribute is always issued by the service provider and  MUST NOT be specified by the client..</param>
        /// <param name="externalId">A String that is an identifier for the resource as defined by the  provisioning client.The \&quot;externalId\&quot; may simplify identification  of a resource between the provisioning client and the service  provider by allowing the client to use a filter to locate the  resource with an identifier from the provisioning domain,  obviating the need to store a local mapping between the  provisioning domain&#39;s identifier of the resource and the  identifier used by the service provider. Each resource MAY  include a non-empty \&quot;externalId\&quot; value. The value of the  \&quot;externalId\&quot; attribute is always issued by the provisioning client  and MUST NOT be specified by the service provider. The service  provider MUST always interpret the externalId as scoped to the  provisioning domain. While the server does not enforce  uniqueness, it is assumed that the value&#39;s uniqueness is  controlled by the client setting the value.See Section 9 for  additional considerations regarding privacy..</param>
        /// <param name="displayName">The name of the user, suitable for display to end-users.  Each  user returned MAY include a non-empty displayName value.  The name  SHOULD be the full name of the User being described, if known  (e.g., \&quot;Babs Jensen\&quot; or \&quot;Ms. Barbara J Jensen, III\&quot;) but MAY be a  username or handle, if that is all that is available (e.g.,  \&quot;bjensen\&quot;).  The value provided SHOULD be the primary textual  label by which this User is normally displayed by the service  provider when presenting it to end-users..</param>
        /// <param name="name">name.</param>
        /// <param name="contactInformation">contactInformation.</param>
        /// <param name="notificationPreferences">notificationPreferences.</param>
        public UserProfile(string tenantId = default(string), List<string> directories = default(List<string>), string id = default(string), string externalId = default(string), string displayName = default(string), PersonName name = default(PersonName), ContactInformation contactInformation = default(ContactInformation), NotificationPreferences notificationPreferences = default(NotificationPreferences))
        {
            this.TenantId = tenantId;
            this.Directories = directories;
            this.Id = id;
            this.ExternalId = externalId;
            this.DisplayName = displayName;
            this.Name = name;
            this.ContactInformation = contactInformation;
            this.NotificationPreferences = notificationPreferences;
        }

        /// <summary>
        /// Identifier for the Tenant this resource belongs to.
        /// </summary>
        /// <value>Identifier for the Tenant this resource belongs to.</value>
        [DataMember(Name = "tenantId", EmitDefaultValue = true)]
        public string TenantId { get; set; }

        /// <summary>
        /// The set of Directory Tags this resource belongs to. A UserProfile may belong to multiple directories.
        /// </summary>
        /// <value>The set of Directory Tags this resource belongs to. A UserProfile may belong to multiple directories.</value>
        [DataMember(Name = "directories", EmitDefaultValue = true)]
        public List<string> Directories { get; set; }

        /// <summary>
        /// A unique identifier for a SCIM resource as defined by the service  provider. Each representation of the resource MUST include a  non-empty \&quot;id\&quot; value.This identifier MUST be unique across the  SCIM service provider&#39;s entire set of resources. It MUST be a  stable, non-reassignable identifier that does not change when the  same resource is returned in subsequent requests.The value of  the \&quot;id\&quot; attribute is always issued by the service provider and  MUST NOT be specified by the client.
        /// </summary>
        /// <value>A unique identifier for a SCIM resource as defined by the service  provider. Each representation of the resource MUST include a  non-empty \&quot;id\&quot; value.This identifier MUST be unique across the  SCIM service provider&#39;s entire set of resources. It MUST be a  stable, non-reassignable identifier that does not change when the  same resource is returned in subsequent requests.The value of  the \&quot;id\&quot; attribute is always issued by the service provider and  MUST NOT be specified by the client.</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// A String that is an identifier for the resource as defined by the  provisioning client.The \&quot;externalId\&quot; may simplify identification  of a resource between the provisioning client and the service  provider by allowing the client to use a filter to locate the  resource with an identifier from the provisioning domain,  obviating the need to store a local mapping between the  provisioning domain&#39;s identifier of the resource and the  identifier used by the service provider. Each resource MAY  include a non-empty \&quot;externalId\&quot; value. The value of the  \&quot;externalId\&quot; attribute is always issued by the provisioning client  and MUST NOT be specified by the service provider. The service  provider MUST always interpret the externalId as scoped to the  provisioning domain. While the server does not enforce  uniqueness, it is assumed that the value&#39;s uniqueness is  controlled by the client setting the value.See Section 9 for  additional considerations regarding privacy.
        /// </summary>
        /// <value>A String that is an identifier for the resource as defined by the  provisioning client.The \&quot;externalId\&quot; may simplify identification  of a resource between the provisioning client and the service  provider by allowing the client to use a filter to locate the  resource with an identifier from the provisioning domain,  obviating the need to store a local mapping between the  provisioning domain&#39;s identifier of the resource and the  identifier used by the service provider. Each resource MAY  include a non-empty \&quot;externalId\&quot; value. The value of the  \&quot;externalId\&quot; attribute is always issued by the provisioning client  and MUST NOT be specified by the service provider. The service  provider MUST always interpret the externalId as scoped to the  provisioning domain. While the server does not enforce  uniqueness, it is assumed that the value&#39;s uniqueness is  controlled by the client setting the value.See Section 9 for  additional considerations regarding privacy.</value>
        [DataMember(Name = "externalId", EmitDefaultValue = true)]
        public string ExternalId { get; set; }

        /// <summary>
        /// The name of the user, suitable for display to end-users.  Each  user returned MAY include a non-empty displayName value.  The name  SHOULD be the full name of the User being described, if known  (e.g., \&quot;Babs Jensen\&quot; or \&quot;Ms. Barbara J Jensen, III\&quot;) but MAY be a  username or handle, if that is all that is available (e.g.,  \&quot;bjensen\&quot;).  The value provided SHOULD be the primary textual  label by which this User is normally displayed by the service  provider when presenting it to end-users.
        /// </summary>
        /// <value>The name of the user, suitable for display to end-users.  Each  user returned MAY include a non-empty displayName value.  The name  SHOULD be the full name of the User being described, if known  (e.g., \&quot;Babs Jensen\&quot; or \&quot;Ms. Barbara J Jensen, III\&quot;) but MAY be a  username or handle, if that is all that is available (e.g.,  \&quot;bjensen\&quot;).  The value provided SHOULD be the primary textual  label by which this User is normally displayed by the service  provider when presenting it to end-users.</value>
        [DataMember(Name = "displayName", EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public PersonName Name { get; set; }

        /// <summary>
        /// Gets or Sets ContactInformation
        /// </summary>
        [DataMember(Name = "contactInformation", EmitDefaultValue = false)]
        public ContactInformation ContactInformation { get; set; }

        /// <summary>
        /// Gets or Sets NotificationPreferences
        /// </summary>
        [DataMember(Name = "notificationPreferences", EmitDefaultValue = false)]
        public NotificationPreferences NotificationPreferences { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserProfile {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  Directories: ").Append(Directories).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ContactInformation: ").Append(ContactInformation).Append("\n");
            sb.Append("  NotificationPreferences: ").Append(NotificationPreferences).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserProfile);
        }

        /// <summary>
        /// Returns true if UserProfile instances are equal
        /// </summary>
        /// <param name="input">Instance of UserProfile to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserProfile input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TenantId == input.TenantId ||
                    (this.TenantId != null &&
                    this.TenantId.Equals(input.TenantId))
                ) && 
                (
                    this.Directories == input.Directories ||
                    this.Directories != null &&
                    input.Directories != null &&
                    this.Directories.SequenceEqual(input.Directories)
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ExternalId == input.ExternalId ||
                    (this.ExternalId != null &&
                    this.ExternalId.Equals(input.ExternalId))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ContactInformation == input.ContactInformation ||
                    (this.ContactInformation != null &&
                    this.ContactInformation.Equals(input.ContactInformation))
                ) && 
                (
                    this.NotificationPreferences == input.NotificationPreferences ||
                    (this.NotificationPreferences != null &&
                    this.NotificationPreferences.Equals(input.NotificationPreferences))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TenantId != null)
                {
                    hashCode = (hashCode * 59) + this.TenantId.GetHashCode();
                }
                if (this.Directories != null)
                {
                    hashCode = (hashCode * 59) + this.Directories.GetHashCode();
                }
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.ExternalId != null)
                {
                    hashCode = (hashCode * 59) + this.ExternalId.GetHashCode();
                }
                if (this.DisplayName != null)
                {
                    hashCode = (hashCode * 59) + this.DisplayName.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.ContactInformation != null)
                {
                    hashCode = (hashCode * 59) + this.ContactInformation.GetHashCode();
                }
                if (this.NotificationPreferences != null)
                {
                    hashCode = (hashCode * 59) + this.NotificationPreferences.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
