/*
 * Public Directory API
 *
 * <p>Working draft of the Konexus Public User directory API.</p><p>This API will be used to allow citizens to create and manage their UserProfiles including contact information and notification preferences. UserProfiles are allowed to contain multiple Emails, Phones, and Locations.</p><p>Weather Notification subscriptions are currently missing from the specification.
 *
 * The version of the OpenAPI document: 4.2.1
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// VerifyEmailCommand
    /// </summary>
    [DataContract(Name = "VerifyEmailCommand")]
    public partial class VerifyEmailCommand : IEquatable<VerifyEmailCommand>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyEmailCommand" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VerifyEmailCommand() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyEmailCommand" /> class.
        /// </summary>
        /// <param name="verificationCode">verificationCode (required).</param>
        public VerifyEmailCommand(string verificationCode = default(string))
        {
            // to ensure "verificationCode" is required (not null)
            if (verificationCode == null)
            {
                throw new ArgumentNullException("verificationCode is a required property for VerifyEmailCommand and cannot be null");
            }
            this.VerificationCode = verificationCode;
        }

        /// <summary>
        /// Gets or Sets VerificationCode
        /// </summary>
        [DataMember(Name = "verificationCode", IsRequired = true, EmitDefaultValue = true)]
        public string VerificationCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VerifyEmailCommand {\n");
            sb.Append("  VerificationCode: ").Append(VerificationCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VerifyEmailCommand);
        }

        /// <summary>
        /// Returns true if VerifyEmailCommand instances are equal
        /// </summary>
        /// <param name="input">Instance of VerifyEmailCommand to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VerifyEmailCommand input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.VerificationCode == input.VerificationCode ||
                    (this.VerificationCode != null &&
                    this.VerificationCode.Equals(input.VerificationCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.VerificationCode != null)
                {
                    hashCode = (hashCode * 59) + this.VerificationCode.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // VerificationCode (string) minLength
            if (this.VerificationCode != null && this.VerificationCode.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for VerificationCode, length must be greater than 1.", new [] { "VerificationCode" });
            }

            yield break;
        }
    }

}
