/*
 * Konexus Platform API - Directory
 *
 * <p>Working draft of the Konexus Platform API - Directory Module</p>
 *
 * The version of the OpenAPI document: 4.2.3
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// VerificationResponse
    /// </summary>
    [DataContract(Name = "VerificationResponse")]
    public partial class VerificationResponse : IEquatable<VerificationResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerificationResponse" /> class.
        /// </summary>
        /// <param name="success">Specifies if the verification successful..</param>
        /// <param name="message">Description of the Verification..</param>
        public VerificationResponse(bool success = default(bool), string message = default(string))
        {
            this.Success = success;
            this.Message = message;
        }

        /// <summary>
        /// Specifies if the verification successful.
        /// </summary>
        /// <value>Specifies if the verification successful.</value>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Description of the Verification.
        /// </summary>
        /// <value>Description of the Verification.</value>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VerificationResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VerificationResponse);
        }

        /// <summary>
        /// Returns true if VerificationResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of VerificationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VerificationResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Success == input.Success ||
                    this.Success.Equals(input.Success)
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Success.GetHashCode();
                if (this.Message != null)
                {
                    hashCode = (hashCode * 59) + this.Message.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
