/*
 * Public Directory API
 *
 * <p>Working draft of the Konexus Public User directory API.</p><p>This API will be used to allow citizens to create and manage their UserProfiles including contact information and notification preferences. UserProfiles are allowed to contain multiple Emails, Phones, and Locations.</p><p>Weather Notification subscriptions are currently missing from the specification.
 *
 * The version of the OpenAPI document: 4.2.0
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// VerificationStatus
    /// </summary>
    [DataContract(Name = "VerificationStatus")]
    public partial class VerificationStatus : IEquatable<VerificationStatus>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerificationStatus" /> class.
        /// </summary>
        /// <param name="verified">verified.</param>
        /// <param name="lastVerificationAttempt">lastVerificationAttempt.</param>
        /// <param name="verificationDate">verificationDate.</param>
        public VerificationStatus(bool verified = default(bool), VerificationAttempt lastVerificationAttempt = default(VerificationAttempt), DateTime? verificationDate = default(DateTime?))
        {
            this.Verified = verified;
            this.LastVerificationAttempt = lastVerificationAttempt;
            this.VerificationDate = verificationDate;
        }

        /// <summary>
        /// Gets or Sets Verified
        /// </summary>
        [DataMember(Name = "verified", EmitDefaultValue = true)]
        public bool Verified { get; set; }

        /// <summary>
        /// Gets or Sets LastVerificationAttempt
        /// </summary>
        [DataMember(Name = "lastVerificationAttempt", EmitDefaultValue = false)]
        public VerificationAttempt LastVerificationAttempt { get; set; }

        /// <summary>
        /// Gets or Sets VerificationDate
        /// </summary>
        [DataMember(Name = "verificationDate", EmitDefaultValue = true)]
        public DateTime? VerificationDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VerificationStatus {\n");
            sb.Append("  Verified: ").Append(Verified).Append("\n");
            sb.Append("  LastVerificationAttempt: ").Append(LastVerificationAttempt).Append("\n");
            sb.Append("  VerificationDate: ").Append(VerificationDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VerificationStatus);
        }

        /// <summary>
        /// Returns true if VerificationStatus instances are equal
        /// </summary>
        /// <param name="input">Instance of VerificationStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VerificationStatus input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Verified == input.Verified ||
                    this.Verified.Equals(input.Verified)
                ) && 
                (
                    this.LastVerificationAttempt == input.LastVerificationAttempt ||
                    (this.LastVerificationAttempt != null &&
                    this.LastVerificationAttempt.Equals(input.LastVerificationAttempt))
                ) && 
                (
                    this.VerificationDate == input.VerificationDate ||
                    (this.VerificationDate != null &&
                    this.VerificationDate.Equals(input.VerificationDate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Verified.GetHashCode();
                if (this.LastVerificationAttempt != null)
                {
                    hashCode = (hashCode * 59) + this.LastVerificationAttempt.GetHashCode();
                }
                if (this.VerificationDate != null)
                {
                    hashCode = (hashCode * 59) + this.VerificationDate.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
