/*
 * Konexus Platform API - Directory
 *
 * <p>Working draft of the Konexus Platform API - Directory Module</p>
 *
 * The version of the OpenAPI document: 4.3.1
 * Contact: dev@konexus.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Directory.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Directory.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Directory.ApiClient.Model
{
    /// <summary>
    /// WeatherNotificationCommand
    /// </summary>
    [DataContract(Name = "WeatherNotificationCommand")]
    public partial class WeatherNotificationCommand : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WeatherNotificationCommand" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WeatherNotificationCommand() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WeatherNotificationCommand" /> class.
        /// </summary>
        /// <param name="categoryId">categoryId (required).</param>
        /// <param name="channels">channels (required).</param>
        public WeatherNotificationCommand(string categoryId = default(string), List<WeatherChannel> channels = default(List<WeatherChannel>))
        {
            // to ensure "categoryId" is required (not null)
            if (categoryId == null)
            {
                throw new ArgumentNullException("categoryId is a required property for WeatherNotificationCommand and cannot be null");
            }
            this.CategoryId = categoryId;
            // to ensure "channels" is required (not null)
            if (channels == null)
            {
                throw new ArgumentNullException("channels is a required property for WeatherNotificationCommand and cannot be null");
            }
            this.Channels = channels;
        }

        /// <summary>
        /// Gets or Sets CategoryId
        /// </summary>
        [DataMember(Name = "categoryId", IsRequired = true, EmitDefaultValue = true)]
        public string CategoryId { get; set; }

        /// <summary>
        /// Gets or Sets Channels
        /// </summary>
        [DataMember(Name = "channels", IsRequired = true, EmitDefaultValue = true)]
        public List<WeatherChannel> Channels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WeatherNotificationCommand {\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  Channels: ").Append(Channels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CategoryId (string) minLength
            if (this.CategoryId != null && this.CategoryId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CategoryId, length must be greater than 1.", new [] { "CategoryId" });
            }

            yield break;
        }
    }

}
