/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Konexus.Alerting.ApiClient.Client;
using Konexus.Alerting.ApiClient.Model;

namespace Konexus.Alerting.ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContactsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a distribution list from a CSV file structured after /v2/contacts/export
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId">Id of the tenant</param>
        /// <param name="createDistributionListFromFileRequest">The file to create the list from.</param>
        /// <returns>CreateDistributionListFromFileResponse</returns>
        CreateDistributionListFromFileResponse CreateFromFile(int tenantId, CreateDistributionListFromFileRequest createDistributionListFromFileRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a distribution list from a CSV file structured after /v2/contacts/export
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId">Id of the tenant</param>
        /// <param name="createDistributionListFromFileRequest">The file to create the list from.</param>
        /// <returns>ApiResponse of CreateDistributionListFromFileResponse</returns>
        ApiResponse<CreateDistributionListFromFileResponse> CreateFromFileWithHttpInfo(int tenantId, CreateDistributionListFromFileRequest createDistributionListFromFileRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a paged list of the contacts.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Filters for contact search (optional)</param>
        /// <returns>PagedContactResponse</returns>
        PagedContactResponse FindContacts(FindContactRequest body = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a paged list of the contacts.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Filters for contact search (optional)</param>
        /// <returns>ApiResponse of PagedContactResponse</returns>
        ApiResponse<PagedContactResponse> FindContactsWithHttpInfo(FindContactRequest body = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Results for all the recipients who have received this specific alert.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the alert</param>
        /// <param name="recipientIds">Filters recipeints by IDs. (optional)</param>
        /// <param name="isMandatory">Filters by recipeints that were mandatory when the alert was sent. (optional)</param>
        /// <param name="pollOptionId">Filters recipeints by the poll option they selected. (optional)</param>
        /// <param name="name">Filters recipeints by name. (optional)</param>
        /// <param name="email">Filters recipeints by email. (optional)</param>
        /// <param name="page">The page number of items to return. (1 by default) (optional, default to 1)</param>
        /// <param name="pageSize">The desired number of items per page. (25 by default) (optional, default to 25)</param>
        /// <param name="sort">A comma seperated list of properties to order by. Properties preceded by a &#39;-&#39; will be ordered descending. (e.g.  ?sort&#x3D;lastName,firstName,-responseTime). Property names are case insensitive. (optional)</param>
        /// <returns>PagedRecipientResponse</returns>
        PagedRecipientResponse GetAlertsByIdRecipients(int id, List<string> recipientIds = default, bool? isMandatory = default, int? pollOptionId = default, string name = default, string email = default, int? page = default, int? pageSize = default, string sort = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Results for all the recipients who have received this specific alert.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the alert</param>
        /// <param name="recipientIds">Filters recipeints by IDs. (optional)</param>
        /// <param name="isMandatory">Filters by recipeints that were mandatory when the alert was sent. (optional)</param>
        /// <param name="pollOptionId">Filters recipeints by the poll option they selected. (optional)</param>
        /// <param name="name">Filters recipeints by name. (optional)</param>
        /// <param name="email">Filters recipeints by email. (optional)</param>
        /// <param name="page">The page number of items to return. (1 by default) (optional, default to 1)</param>
        /// <param name="pageSize">The desired number of items per page. (25 by default) (optional, default to 25)</param>
        /// <param name="sort">A comma seperated list of properties to order by. Properties preceded by a &#39;-&#39; will be ordered descending. (e.g.  ?sort&#x3D;lastName,firstName,-responseTime). Property names are case insensitive. (optional)</param>
        /// <returns>ApiResponse of PagedRecipientResponse</returns>
        ApiResponse<PagedRecipientResponse> GetAlertsByIdRecipientsWithHttpInfo(int id, List<string> recipientIds = default, bool? isMandatory = default, int? pollOptionId = default, string name = default, string email = default, int? page = default, int? pageSize = default, string sort = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Results for the specified recipient who has received this specific alert.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId">Id of the alert</param>
        /// <param name="recipientId">Id of the recipient</param>
        /// <returns>SingleRecipientResponse</returns>
        SingleRecipientResponse GetAlertsByIdSingleRecipient(int alertId, int recipientId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Results for the specified recipient who has received this specific alert.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId">Id of the alert</param>
        /// <param name="recipientId">Id of the recipient</param>
        /// <returns>ApiResponse of SingleRecipientResponse</returns>
        ApiResponse<SingleRecipientResponse> GetAlertsByIdSingleRecipientWithHttpInfo(int alertId, int recipientId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContactsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a distribution list from a CSV file structured after /v2/contacts/export
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId">Id of the tenant</param>
        /// <param name="createDistributionListFromFileRequest">The file to create the list from.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateDistributionListFromFileResponse</returns>
        System.Threading.Tasks.Task<CreateDistributionListFromFileResponse> CreateFromFileAsync(int tenantId, CreateDistributionListFromFileRequest createDistributionListFromFileRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a distribution list from a CSV file structured after /v2/contacts/export
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId">Id of the tenant</param>
        /// <param name="createDistributionListFromFileRequest">The file to create the list from.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateDistributionListFromFileResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateDistributionListFromFileResponse>> CreateFromFileWithHttpInfoAsync(int tenantId, CreateDistributionListFromFileRequest createDistributionListFromFileRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a paged list of the contacts.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Filters for contact search (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PagedContactResponse</returns>
        System.Threading.Tasks.Task<PagedContactResponse> FindContactsAsync(FindContactRequest body = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a paged list of the contacts.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Filters for contact search (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PagedContactResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PagedContactResponse>> FindContactsWithHttpInfoAsync(FindContactRequest body = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Results for all the recipients who have received this specific alert.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the alert</param>
        /// <param name="recipientIds">Filters recipeints by IDs. (optional)</param>
        /// <param name="isMandatory">Filters by recipeints that were mandatory when the alert was sent. (optional)</param>
        /// <param name="pollOptionId">Filters recipeints by the poll option they selected. (optional)</param>
        /// <param name="name">Filters recipeints by name. (optional)</param>
        /// <param name="email">Filters recipeints by email. (optional)</param>
        /// <param name="page">The page number of items to return. (1 by default) (optional, default to 1)</param>
        /// <param name="pageSize">The desired number of items per page. (25 by default) (optional, default to 25)</param>
        /// <param name="sort">A comma seperated list of properties to order by. Properties preceded by a &#39;-&#39; will be ordered descending. (e.g.  ?sort&#x3D;lastName,firstName,-responseTime). Property names are case insensitive. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PagedRecipientResponse</returns>
        System.Threading.Tasks.Task<PagedRecipientResponse> GetAlertsByIdRecipientsAsync(int id, List<string> recipientIds = default, bool? isMandatory = default, int? pollOptionId = default, string name = default, string email = default, int? page = default, int? pageSize = default, string sort = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Results for all the recipients who have received this specific alert.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the alert</param>
        /// <param name="recipientIds">Filters recipeints by IDs. (optional)</param>
        /// <param name="isMandatory">Filters by recipeints that were mandatory when the alert was sent. (optional)</param>
        /// <param name="pollOptionId">Filters recipeints by the poll option they selected. (optional)</param>
        /// <param name="name">Filters recipeints by name. (optional)</param>
        /// <param name="email">Filters recipeints by email. (optional)</param>
        /// <param name="page">The page number of items to return. (1 by default) (optional, default to 1)</param>
        /// <param name="pageSize">The desired number of items per page. (25 by default) (optional, default to 25)</param>
        /// <param name="sort">A comma seperated list of properties to order by. Properties preceded by a &#39;-&#39; will be ordered descending. (e.g.  ?sort&#x3D;lastName,firstName,-responseTime). Property names are case insensitive. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PagedRecipientResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PagedRecipientResponse>> GetAlertsByIdRecipientsWithHttpInfoAsync(int id, List<string> recipientIds = default, bool? isMandatory = default, int? pollOptionId = default, string name = default, string email = default, int? page = default, int? pageSize = default, string sort = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Results for the specified recipient who has received this specific alert.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId">Id of the alert</param>
        /// <param name="recipientId">Id of the recipient</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SingleRecipientResponse</returns>
        System.Threading.Tasks.Task<SingleRecipientResponse> GetAlertsByIdSingleRecipientAsync(int alertId, int recipientId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Results for the specified recipient who has received this specific alert.
        /// </remarks>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId">Id of the alert</param>
        /// <param name="recipientId">Id of the recipient</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SingleRecipientResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SingleRecipientResponse>> GetAlertsByIdSingleRecipientWithHttpInfoAsync(int alertId, int recipientId, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContactsApi : IContactsApiSync, IContactsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ContactsApi : IDisposable, IContactsApi
    {
        private Konexus.Alerting.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ContactsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ContactsApi(string basePath)
        {
            this.Configuration = Konexus.Alerting.ApiClient.Client.Configuration.MergeConfigurations(
                Konexus.Alerting.ApiClient.Client.GlobalConfiguration.Instance,
                new Konexus.Alerting.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Konexus.Alerting.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Konexus.Alerting.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ContactsApi(Konexus.Alerting.ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Konexus.Alerting.ApiClient.Client.Configuration.MergeConfigurations(
                Konexus.Alerting.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Konexus.Alerting.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Konexus.Alerting.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ContactsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ContactsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Konexus.Alerting.ApiClient.Client.Configuration.MergeConfigurations(
                Konexus.Alerting.ApiClient.Client.GlobalConfiguration.Instance,
                new Konexus.Alerting.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Konexus.Alerting.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Konexus.Alerting.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ContactsApi(HttpClient client, Konexus.Alerting.ApiClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Konexus.Alerting.ApiClient.Client.Configuration.MergeConfigurations(
                Konexus.Alerting.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Konexus.Alerting.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Konexus.Alerting.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ContactsApi(Konexus.Alerting.ApiClient.Client.ISynchronousClient client, Konexus.Alerting.ApiClient.Client.IAsynchronousClient asyncClient, Konexus.Alerting.ApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Konexus.Alerting.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Konexus.Alerting.ApiClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Konexus.Alerting.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Konexus.Alerting.ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Konexus.Alerting.ApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Konexus.Alerting.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Creates a distribution list from a CSV file structured after /v2/contacts/export
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId">Id of the tenant</param>
        /// <param name="createDistributionListFromFileRequest">The file to create the list from.</param>
        /// <returns>CreateDistributionListFromFileResponse</returns>
        public CreateDistributionListFromFileResponse CreateFromFile(int tenantId, CreateDistributionListFromFileRequest createDistributionListFromFileRequest)
        {
            Konexus.Alerting.ApiClient.Client.ApiResponse<CreateDistributionListFromFileResponse> localVarResponse = CreateFromFileWithHttpInfo(tenantId, createDistributionListFromFileRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Creates a distribution list from a CSV file structured after /v2/contacts/export
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId">Id of the tenant</param>
        /// <param name="createDistributionListFromFileRequest">The file to create the list from.</param>
        /// <returns>ApiResponse of CreateDistributionListFromFileResponse</returns>
        public Konexus.Alerting.ApiClient.Client.ApiResponse<CreateDistributionListFromFileResponse> CreateFromFileWithHttpInfo(int tenantId, CreateDistributionListFromFileRequest createDistributionListFromFileRequest)
        {
            // verify the required parameter 'createDistributionListFromFileRequest' is set
            if (createDistributionListFromFileRequest == null)
                throw new Konexus.Alerting.ApiClient.Client.ApiException(400, "Missing required parameter 'createDistributionListFromFileRequest' when calling ContactsApi->CreateFromFile");

            Konexus.Alerting.ApiClient.Client.RequestOptions localVarRequestOptions = new Konexus.Alerting.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("tenantId", Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            localVarRequestOptions.Data = createDistributionListFromFileRequest;

            // authentication (Oauth2Scheme) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (JwtBearerTokenScheme) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateDistributionListFromFileResponse>("/v4/{tenantId}/distributionLists/createFromFile", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateFromFile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Creates a distribution list from a CSV file structured after /v2/contacts/export
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId">Id of the tenant</param>
        /// <param name="createDistributionListFromFileRequest">The file to create the list from.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateDistributionListFromFileResponse</returns>
        public async System.Threading.Tasks.Task<CreateDistributionListFromFileResponse> CreateFromFileAsync(int tenantId, CreateDistributionListFromFileRequest createDistributionListFromFileRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Konexus.Alerting.ApiClient.Client.ApiResponse<CreateDistributionListFromFileResponse> localVarResponse = await CreateFromFileWithHttpInfoAsync(tenantId, createDistributionListFromFileRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Creates a distribution list from a CSV file structured after /v2/contacts/export
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId">Id of the tenant</param>
        /// <param name="createDistributionListFromFileRequest">The file to create the list from.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateDistributionListFromFileResponse)</returns>
        public async System.Threading.Tasks.Task<Konexus.Alerting.ApiClient.Client.ApiResponse<CreateDistributionListFromFileResponse>> CreateFromFileWithHttpInfoAsync(int tenantId, CreateDistributionListFromFileRequest createDistributionListFromFileRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createDistributionListFromFileRequest' is set
            if (createDistributionListFromFileRequest == null)
                throw new Konexus.Alerting.ApiClient.Client.ApiException(400, "Missing required parameter 'createDistributionListFromFileRequest' when calling ContactsApi->CreateFromFile");


            Konexus.Alerting.ApiClient.Client.RequestOptions localVarRequestOptions = new Konexus.Alerting.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("tenantId", Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            localVarRequestOptions.Data = createDistributionListFromFileRequest;

            // authentication (Oauth2Scheme) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (JwtBearerTokenScheme) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateDistributionListFromFileResponse>("/v4/{tenantId}/distributionLists/createFromFile", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateFromFile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Returns a paged list of the contacts.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Filters for contact search (optional)</param>
        /// <returns>PagedContactResponse</returns>
        public PagedContactResponse FindContacts(FindContactRequest body = default)
        {
            Konexus.Alerting.ApiClient.Client.ApiResponse<PagedContactResponse> localVarResponse = FindContactsWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns a paged list of the contacts.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Filters for contact search (optional)</param>
        /// <returns>ApiResponse of PagedContactResponse</returns>
        public Konexus.Alerting.ApiClient.Client.ApiResponse<PagedContactResponse> FindContactsWithHttpInfo(FindContactRequest body = default)
        {
            Konexus.Alerting.ApiClient.Client.RequestOptions localVarRequestOptions = new Konexus.Alerting.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;

            // authentication (Oauth2Scheme) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (JwtBearerTokenScheme) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PagedContactResponse>("/v2/contacts/find", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindContacts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Returns a paged list of the contacts.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Filters for contact search (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PagedContactResponse</returns>
        public async System.Threading.Tasks.Task<PagedContactResponse> FindContactsAsync(FindContactRequest body = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Konexus.Alerting.ApiClient.Client.ApiResponse<PagedContactResponse> localVarResponse = await FindContactsWithHttpInfoAsync(body, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns a paged list of the contacts.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Filters for contact search (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PagedContactResponse)</returns>
        public async System.Threading.Tasks.Task<Konexus.Alerting.ApiClient.Client.ApiResponse<PagedContactResponse>> FindContactsWithHttpInfoAsync(FindContactRequest body = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Konexus.Alerting.ApiClient.Client.RequestOptions localVarRequestOptions = new Konexus.Alerting.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;

            // authentication (Oauth2Scheme) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (JwtBearerTokenScheme) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PagedContactResponse>("/v2/contacts/find", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FindContacts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Results for all the recipients who have received this specific alert.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the alert</param>
        /// <param name="recipientIds">Filters recipeints by IDs. (optional)</param>
        /// <param name="isMandatory">Filters by recipeints that were mandatory when the alert was sent. (optional)</param>
        /// <param name="pollOptionId">Filters recipeints by the poll option they selected. (optional)</param>
        /// <param name="name">Filters recipeints by name. (optional)</param>
        /// <param name="email">Filters recipeints by email. (optional)</param>
        /// <param name="page">The page number of items to return. (1 by default) (optional, default to 1)</param>
        /// <param name="pageSize">The desired number of items per page. (25 by default) (optional, default to 25)</param>
        /// <param name="sort">A comma seperated list of properties to order by. Properties preceded by a &#39;-&#39; will be ordered descending. (e.g.  ?sort&#x3D;lastName,firstName,-responseTime). Property names are case insensitive. (optional)</param>
        /// <returns>PagedRecipientResponse</returns>
        public PagedRecipientResponse GetAlertsByIdRecipients(int id, List<string> recipientIds = default, bool? isMandatory = default, int? pollOptionId = default, string name = default, string email = default, int? page = default, int? pageSize = default, string sort = default)
        {
            Konexus.Alerting.ApiClient.Client.ApiResponse<PagedRecipientResponse> localVarResponse = GetAlertsByIdRecipientsWithHttpInfo(id, recipientIds, isMandatory, pollOptionId, name, email, page, pageSize, sort);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Results for all the recipients who have received this specific alert.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the alert</param>
        /// <param name="recipientIds">Filters recipeints by IDs. (optional)</param>
        /// <param name="isMandatory">Filters by recipeints that were mandatory when the alert was sent. (optional)</param>
        /// <param name="pollOptionId">Filters recipeints by the poll option they selected. (optional)</param>
        /// <param name="name">Filters recipeints by name. (optional)</param>
        /// <param name="email">Filters recipeints by email. (optional)</param>
        /// <param name="page">The page number of items to return. (1 by default) (optional, default to 1)</param>
        /// <param name="pageSize">The desired number of items per page. (25 by default) (optional, default to 25)</param>
        /// <param name="sort">A comma seperated list of properties to order by. Properties preceded by a &#39;-&#39; will be ordered descending. (e.g.  ?sort&#x3D;lastName,firstName,-responseTime). Property names are case insensitive. (optional)</param>
        /// <returns>ApiResponse of PagedRecipientResponse</returns>
        public Konexus.Alerting.ApiClient.Client.ApiResponse<PagedRecipientResponse> GetAlertsByIdRecipientsWithHttpInfo(int id, List<string> recipientIds = default, bool? isMandatory = default, int? pollOptionId = default, string name = default, string email = default, int? page = default, int? pageSize = default, string sort = default)
        {
            Konexus.Alerting.ApiClient.Client.RequestOptions localVarRequestOptions = new Konexus.Alerting.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (recipientIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("csv", "recipientIds", recipientIds));
            }
            if (isMandatory != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "isMandatory", isMandatory));
            }
            if (pollOptionId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "pollOptionId", pollOptionId));
            }
            if (name != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "name", name));
            }
            if (email != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "email", email));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }

            // authentication (Oauth2Scheme) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (JwtBearerTokenScheme) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<PagedRecipientResponse>("/v2/alerts/{id}/results/recipients", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAlertsByIdRecipients", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Results for all the recipients who have received this specific alert.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the alert</param>
        /// <param name="recipientIds">Filters recipeints by IDs. (optional)</param>
        /// <param name="isMandatory">Filters by recipeints that were mandatory when the alert was sent. (optional)</param>
        /// <param name="pollOptionId">Filters recipeints by the poll option they selected. (optional)</param>
        /// <param name="name">Filters recipeints by name. (optional)</param>
        /// <param name="email">Filters recipeints by email. (optional)</param>
        /// <param name="page">The page number of items to return. (1 by default) (optional, default to 1)</param>
        /// <param name="pageSize">The desired number of items per page. (25 by default) (optional, default to 25)</param>
        /// <param name="sort">A comma seperated list of properties to order by. Properties preceded by a &#39;-&#39; will be ordered descending. (e.g.  ?sort&#x3D;lastName,firstName,-responseTime). Property names are case insensitive. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PagedRecipientResponse</returns>
        public async System.Threading.Tasks.Task<PagedRecipientResponse> GetAlertsByIdRecipientsAsync(int id, List<string> recipientIds = default, bool? isMandatory = default, int? pollOptionId = default, string name = default, string email = default, int? page = default, int? pageSize = default, string sort = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Konexus.Alerting.ApiClient.Client.ApiResponse<PagedRecipientResponse> localVarResponse = await GetAlertsByIdRecipientsWithHttpInfoAsync(id, recipientIds, isMandatory, pollOptionId, name, email, page, pageSize, sort, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Results for all the recipients who have received this specific alert.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Id of the alert</param>
        /// <param name="recipientIds">Filters recipeints by IDs. (optional)</param>
        /// <param name="isMandatory">Filters by recipeints that were mandatory when the alert was sent. (optional)</param>
        /// <param name="pollOptionId">Filters recipeints by the poll option they selected. (optional)</param>
        /// <param name="name">Filters recipeints by name. (optional)</param>
        /// <param name="email">Filters recipeints by email. (optional)</param>
        /// <param name="page">The page number of items to return. (1 by default) (optional, default to 1)</param>
        /// <param name="pageSize">The desired number of items per page. (25 by default) (optional, default to 25)</param>
        /// <param name="sort">A comma seperated list of properties to order by. Properties preceded by a &#39;-&#39; will be ordered descending. (e.g.  ?sort&#x3D;lastName,firstName,-responseTime). Property names are case insensitive. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PagedRecipientResponse)</returns>
        public async System.Threading.Tasks.Task<Konexus.Alerting.ApiClient.Client.ApiResponse<PagedRecipientResponse>> GetAlertsByIdRecipientsWithHttpInfoAsync(int id, List<string> recipientIds = default, bool? isMandatory = default, int? pollOptionId = default, string name = default, string email = default, int? page = default, int? pageSize = default, string sort = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Konexus.Alerting.ApiClient.Client.RequestOptions localVarRequestOptions = new Konexus.Alerting.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (recipientIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("csv", "recipientIds", recipientIds));
            }
            if (isMandatory != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "isMandatory", isMandatory));
            }
            if (pollOptionId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "pollOptionId", pollOptionId));
            }
            if (name != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "name", name));
            }
            if (email != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "email", email));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }

            // authentication (Oauth2Scheme) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (JwtBearerTokenScheme) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<PagedRecipientResponse>("/v2/alerts/{id}/results/recipients", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAlertsByIdRecipients", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Results for the specified recipient who has received this specific alert.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId">Id of the alert</param>
        /// <param name="recipientId">Id of the recipient</param>
        /// <returns>SingleRecipientResponse</returns>
        public SingleRecipientResponse GetAlertsByIdSingleRecipient(int alertId, int recipientId)
        {
            Konexus.Alerting.ApiClient.Client.ApiResponse<SingleRecipientResponse> localVarResponse = GetAlertsByIdSingleRecipientWithHttpInfo(alertId, recipientId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Results for the specified recipient who has received this specific alert.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId">Id of the alert</param>
        /// <param name="recipientId">Id of the recipient</param>
        /// <returns>ApiResponse of SingleRecipientResponse</returns>
        public Konexus.Alerting.ApiClient.Client.ApiResponse<SingleRecipientResponse> GetAlertsByIdSingleRecipientWithHttpInfo(int alertId, int recipientId)
        {
            Konexus.Alerting.ApiClient.Client.RequestOptions localVarRequestOptions = new Konexus.Alerting.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("alertId", Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToString(alertId)); // path parameter
            localVarRequestOptions.PathParameters.Add("recipientId", Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToString(recipientId)); // path parameter

            // authentication (Oauth2Scheme) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (JwtBearerTokenScheme) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<SingleRecipientResponse>("/v2/alerts/{alertId}/results/recipients/{recipientId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAlertsByIdSingleRecipient", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Results for the specified recipient who has received this specific alert.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId">Id of the alert</param>
        /// <param name="recipientId">Id of the recipient</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SingleRecipientResponse</returns>
        public async System.Threading.Tasks.Task<SingleRecipientResponse> GetAlertsByIdSingleRecipientAsync(int alertId, int recipientId, System.Threading.CancellationToken cancellationToken = default)
        {
            Konexus.Alerting.ApiClient.Client.ApiResponse<SingleRecipientResponse> localVarResponse = await GetAlertsByIdSingleRecipientWithHttpInfoAsync(alertId, recipientId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Results for the specified recipient who has received this specific alert.
        /// </summary>
        /// <exception cref="Konexus.Alerting.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId">Id of the alert</param>
        /// <param name="recipientId">Id of the recipient</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SingleRecipientResponse)</returns>
        public async System.Threading.Tasks.Task<Konexus.Alerting.ApiClient.Client.ApiResponse<SingleRecipientResponse>> GetAlertsByIdSingleRecipientWithHttpInfoAsync(int alertId, int recipientId, System.Threading.CancellationToken cancellationToken = default)
        {

            Konexus.Alerting.ApiClient.Client.RequestOptions localVarRequestOptions = new Konexus.Alerting.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Konexus.Alerting.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("alertId", Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToString(alertId)); // path parameter
            localVarRequestOptions.PathParameters.Add("recipientId", Konexus.Alerting.ApiClient.Client.ClientUtils.ParameterToString(recipientId)); // path parameter

            // authentication (Oauth2Scheme) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (JwtBearerTokenScheme) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<SingleRecipientResponse>("/v2/alerts/{alertId}/results/recipients/{recipientId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAlertsByIdSingleRecipient", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
