/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// Defines AlertType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AlertType
    {
        /// <summary>
        /// Enum Unused for value: Unused
        /// </summary>
        [EnumMember(Value = "Unused")]
        Unused = 1,

        /// <summary>
        /// Enum Default for value: Default
        /// </summary>
        [EnumMember(Value = "Default")]
        Default = 2,

        /// <summary>
        /// Enum Poll for value: Poll
        /// </summary>
        [EnumMember(Value = "Poll")]
        Poll = 3,

        /// <summary>
        /// Enum Conference for value: Conference
        /// </summary>
        [EnumMember(Value = "Conference")]
        Conference = 4
    }

}
