/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// AlertDefaults
    /// </summary>
    [DataContract(Name = "AlertDefaults")]
    public partial class AlertDefaults : AlertSettings, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlertDefaults" /> class.
        /// </summary>
        /// <param name="fields">fields.</param>
        /// <param name="severityAssessmentId">severityAssessmentId.</param>
        /// <param name="alertType">alertType.</param>
        /// <param name="weatherAlert">weatherAlert.</param>
        /// <param name="capKey">capKey.</param>
        /// <param name="capXml">capXml.</param>
        /// <param name="channels">channels.</param>
        /// <param name="formType">formType.</param>
        /// <param name="id">id.</param>
        /// <param name="facilities">facilities.</param>
        /// <param name="location">location.</param>
        /// <param name="message">message.</param>
        /// <param name="recipients">recipients.</param>
        /// <param name="mobileBroadcast">mobileBroadcast.</param>
        /// <param name="regionId">regionId.</param>
        /// <param name="regionName">regionName.</param>
        /// <param name="related">related.</param>
        /// <param name="schedule">schedule.</param>
        /// <param name="security">security.</param>
        /// <param name="sender">sender.</param>
        /// <param name="timeSent">timeSent.</param>
        /// <param name="userId">userId.</param>
        /// <param name="workflow">workflow.</param>
        /// <param name="prioritySettings">prioritySettings.</param>
        /// <param name="hidden">hidden.</param>
        /// <param name="completionStatus">completionStatus.</param>
        /// <param name="brandId">brandId.</param>
        /// <param name="relatedAlertActions">relatedAlertActions.</param>
        /// <param name="pipelineSettings">pipelineSettings.</param>
        /// <param name="publicAlert">publicAlert.</param>
        /// <param name="requestConfirmation">requestConfirmation.</param>
        /// <param name="clientContext">clientContext.</param>
        public AlertDefaults(List<Field> fields = default, string severityAssessmentId = default, AlertType? alertType = default, bool weatherAlert = default, string capKey = default, string capXml = default, ChannelSettings channels = default, FormType? formType = default, int id = default, FacilitySettings facilities = default, LocationSettings location = default, MessageSettings message = default, RecipientSettings recipients = default, MobileBroadcastSettings mobileBroadcast = default, int regionId = default, string regionName = default, List<RelatedAlert> related = default, ScheduleSettings schedule = default, SecuritySettings security = default, SenderSettings sender = default, DateTime timeSent = default, int userId = default, WorkflowSettings workflow = default, PrioritySettings prioritySettings = default, bool hidden = default, AlertStatus completionStatus = default, int brandId = default, RelatedAlertActions relatedAlertActions = default, PipelineSettings pipelineSettings = default, bool publicAlert = default, bool requestConfirmation = default, ClientRequestContext clientContext = default) : base(alertType, weatherAlert, capKey, capXml, channels, formType, id, facilities, location, message, recipients, mobileBroadcast, regionId, regionName, related, schedule, security, sender, timeSent, userId, workflow, prioritySettings, hidden, completionStatus, brandId, relatedAlertActions, pipelineSettings, publicAlert, requestConfirmation, clientContext)
        {
            this.Fields = fields;
            this.SeverityAssessmentId = severityAssessmentId;
        }

        /// <summary>
        /// Gets or Sets Fields
        /// </summary>
        [DataMember(Name = "fields", EmitDefaultValue = false)]
        public List<Field> Fields { get; set; }

        /// <summary>
        /// Gets or Sets SeverityAssessmentId
        /// </summary>
        [DataMember(Name = "severityAssessmentId", EmitDefaultValue = false)]
        public string SeverityAssessmentId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AlertDefaults {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("  SeverityAssessmentId: ").Append(SeverityAssessmentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
