/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// Variable current value
    /// </summary>
    [DataContract(Name = "AlertSettingsValue")]
    public partial class AlertSettingsValue : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [DataMember(Name = "source", EmitDefaultValue = false)]
        public AlertSettingsVariableSource? Source { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AlertSettingsValue" /> class.
        /// </summary>
        /// <param name="friendlyName">Friendly name for this variable.</param>
        /// <param name="placeHolder">Placeholder for this variable.</param>
        /// <param name="source">source.</param>
        /// <param name="maxLength">MaxLength for this variable. This will be used when validating a message length.</param>
        /// <param name="sampleValue">Sample value for this variable.</param>
        /// <param name="template">Template for this variable.</param>
        /// <param name="value">Value for this variable.</param>
        /// <param name="isError">Indicates if there are any validation failures in this response.</param>
        /// <param name="validationFailures">Validation failures of this request object.</param>
        /// <param name="usedMessageVariables">Used variables by Message Variable Source.</param>
        public AlertSettingsValue(string friendlyName = default, string placeHolder = default, AlertSettingsVariableSource? source = default, int maxLength = default, string sampleValue = default, string template = default, string value = default, bool isError = default, List<ValidationFailure> validationFailures = default, Dictionary<string, List<string>> usedMessageVariables = default)
        {
            this.FriendlyName = friendlyName;
            this.PlaceHolder = placeHolder;
            this.Source = source;
            this.MaxLength = maxLength;
            this.SampleValue = sampleValue;
            this.Template = template;
            this.Value = value;
            this.IsError = isError;
            this.ValidationFailures = validationFailures;
            this.UsedMessageVariables = usedMessageVariables;
        }

        /// <summary>
        /// Friendly name for this variable
        /// </summary>
        /// <value>Friendly name for this variable</value>
        [DataMember(Name = "friendlyName", EmitDefaultValue = false)]
        public string FriendlyName { get; set; }

        /// <summary>
        /// Placeholder for this variable
        /// </summary>
        /// <value>Placeholder for this variable</value>
        [DataMember(Name = "placeHolder", EmitDefaultValue = false)]
        public string PlaceHolder { get; set; }

        /// <summary>
        /// MaxLength for this variable. This will be used when validating a message length
        /// </summary>
        /// <value>MaxLength for this variable. This will be used when validating a message length</value>
        [DataMember(Name = "maxLength", EmitDefaultValue = false)]
        public int MaxLength { get; set; }

        /// <summary>
        /// Sample value for this variable
        /// </summary>
        /// <value>Sample value for this variable</value>
        [DataMember(Name = "sampleValue", EmitDefaultValue = false)]
        public string SampleValue { get; set; }

        /// <summary>
        /// Template for this variable
        /// </summary>
        /// <value>Template for this variable</value>
        [DataMember(Name = "template", EmitDefaultValue = false)]
        public string Template { get; set; }

        /// <summary>
        /// Value for this variable
        /// </summary>
        /// <value>Value for this variable</value>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Indicates if there are any validation failures in this response
        /// </summary>
        /// <value>Indicates if there are any validation failures in this response</value>
        [DataMember(Name = "isError", EmitDefaultValue = true)]
        public bool IsError { get; set; }

        /// <summary>
        /// Validation failures of this request object
        /// </summary>
        /// <value>Validation failures of this request object</value>
        [DataMember(Name = "validationFailures", EmitDefaultValue = false)]
        public List<ValidationFailure> ValidationFailures { get; set; }

        /// <summary>
        /// Used variables by Message Variable Source
        /// </summary>
        /// <value>Used variables by Message Variable Source</value>
        [DataMember(Name = "usedMessageVariables", EmitDefaultValue = false)]
        public Dictionary<string, List<string>> UsedMessageVariables { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AlertSettingsValue {\n");
            sb.Append("  FriendlyName: ").Append(FriendlyName).Append("\n");
            sb.Append("  PlaceHolder: ").Append(PlaceHolder).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  MaxLength: ").Append(MaxLength).Append("\n");
            sb.Append("  SampleValue: ").Append(SampleValue).Append("\n");
            sb.Append("  Template: ").Append(Template).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  IsError: ").Append(IsError).Append("\n");
            sb.Append("  ValidationFailures: ").Append(ValidationFailures).Append("\n");
            sb.Append("  UsedMessageVariables: ").Append(UsedMessageVariables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
