/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// ClientRequestContext
    /// </summary>
    [DataContract(Name = "ClientRequestContext")]
    public partial class ClientRequestContext : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClientRequestContext" /> class.
        /// </summary>
        /// <param name="templateId">templateId.</param>
        /// <param name="isResend">isResend.</param>
        /// <param name="platform">platform.</param>
        /// <param name="clientId">clientId.</param>
        /// <param name="clientName">clientName.</param>
        /// <param name="clientVersion">clientVersion.</param>
        /// <param name="deviceId">deviceId.</param>
        public ClientRequestContext(int? templateId = default, bool isResend = default, string platform = default, string clientId = default, string clientName = default, string clientVersion = default, string deviceId = default)
        {
            this.TemplateId = templateId;
            this.IsResend = isResend;
            this.Platform = platform;
            this.ClientId = clientId;
            this.ClientName = clientName;
            this.ClientVersion = clientVersion;
            this.DeviceId = deviceId;
        }

        /// <summary>
        /// Gets or Sets TemplateId
        /// </summary>
        [DataMember(Name = "templateId", EmitDefaultValue = true)]
        public int? TemplateId { get; set; }

        /// <summary>
        /// Gets or Sets IsResend
        /// </summary>
        [DataMember(Name = "isResend", EmitDefaultValue = true)]
        public bool IsResend { get; set; }

        /// <summary>
        /// Gets or Sets Platform
        /// </summary>
        [DataMember(Name = "platform", EmitDefaultValue = false)]
        public string Platform { get; set; }

        /// <summary>
        /// Gets or Sets ClientId
        /// </summary>
        [DataMember(Name = "clientId", EmitDefaultValue = false)]
        public string ClientId { get; set; }

        /// <summary>
        /// Gets or Sets ClientName
        /// </summary>
        [DataMember(Name = "clientName", EmitDefaultValue = false)]
        public string ClientName { get; set; }

        /// <summary>
        /// Gets or Sets ClientVersion
        /// </summary>
        [DataMember(Name = "clientVersion", EmitDefaultValue = false)]
        public string ClientVersion { get; set; }

        /// <summary>
        /// Gets or Sets DeviceId
        /// </summary>
        [DataMember(Name = "deviceId", EmitDefaultValue = false)]
        public string DeviceId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ClientRequestContext {\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  IsResend: ").Append(IsResend).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  ClientName: ").Append(ClientName).Append("\n");
            sb.Append("  ClientVersion: ").Append(ClientVersion).Append("\n");
            sb.Append("  DeviceId: ").Append(DeviceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
