/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// DeliverySummary
    /// </summary>
    [DataContract(Name = "DeliverySummary")]
    public partial class DeliverySummary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeliverySummary" /> class.
        /// </summary>
        /// <param name="delivery">delivery.</param>
        /// <param name="id">id.</param>
        /// <param name="poll">poll.</param>
        /// <param name="mobileBroadcast">mobileBroadcast.</param>
        /// <param name="totalRecipients">totalRecipients.</param>
        public DeliverySummary(Dictionary<string, int> delivery = default, int id = default, PollQuestionResults poll = default, List<MobileBroadcastResultSummary> mobileBroadcast = default, int totalRecipients = default)
        {
            this.Delivery = delivery;
            this.Id = id;
            this.Poll = poll;
            this.MobileBroadcast = mobileBroadcast;
            this.TotalRecipients = totalRecipients;
        }

        /// <summary>
        /// Gets or Sets Delivery
        /// </summary>
        [DataMember(Name = "delivery", EmitDefaultValue = false)]
        public Dictionary<string, int> Delivery { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Poll
        /// </summary>
        [DataMember(Name = "poll", EmitDefaultValue = false)]
        public PollQuestionResults Poll { get; set; }

        /// <summary>
        /// Gets or Sets MobileBroadcast
        /// </summary>
        [DataMember(Name = "mobileBroadcast", EmitDefaultValue = false)]
        public List<MobileBroadcastResultSummary> MobileBroadcast { get; set; }

        /// <summary>
        /// Gets or Sets TotalRecipients
        /// </summary>
        [DataMember(Name = "totalRecipients", EmitDefaultValue = false)]
        public int TotalRecipients { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeliverySummary {\n");
            sb.Append("  Delivery: ").Append(Delivery).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Poll: ").Append(Poll).Append("\n");
            sb.Append("  MobileBroadcast: ").Append(MobileBroadcast).Append("\n");
            sb.Append("  TotalRecipients: ").Append(TotalRecipients).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
