/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// DisplayRole
    /// </summary>
    [DataContract(Name = "DisplayRole")]
    public partial class DisplayRole : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DisplayRole" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="hasFullCommAccess">hasFullCommAccess.</param>
        /// <param name="ignoreMandatoryAlertGroupPolicies">ignoreMandatoryAlertGroupPolicies.</param>
        /// <param name="order">order.</param>
        public DisplayRole(string id = default, string name = default, bool hasFullCommAccess = default, bool ignoreMandatoryAlertGroupPolicies = default, int order = default)
        {
            this.Id = id;
            this.Name = name;
            this.HasFullCommAccess = hasFullCommAccess;
            this.IgnoreMandatoryAlertGroupPolicies = ignoreMandatoryAlertGroupPolicies;
            this.Order = order;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets HasFullCommAccess
        /// </summary>
        [DataMember(Name = "hasFullCommAccess", EmitDefaultValue = true)]
        public bool HasFullCommAccess { get; set; }

        /// <summary>
        /// Gets or Sets IgnoreMandatoryAlertGroupPolicies
        /// </summary>
        [DataMember(Name = "ignoreMandatoryAlertGroupPolicies", EmitDefaultValue = true)]
        public bool IgnoreMandatoryAlertGroupPolicies { get; set; }

        /// <summary>
        /// Gets or Sets Order
        /// </summary>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        public int Order { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DisplayRole {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  HasFullCommAccess: ").Append(HasFullCommAccess).Append("\n");
            sb.Append("  IgnoreMandatoryAlertGroupPolicies: ").Append(IgnoreMandatoryAlertGroupPolicies).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
