/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// DistributionProfile
    /// </summary>
    [DataContract(Name = "DistributionProfile")]
    public partial class DistributionProfile : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DistributionProfile" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId.</param>
        /// <param name="userId">userId.</param>
        /// <param name="externalId">externalId.</param>
        /// <param name="firstName">firstName.</param>
        /// <param name="lastName">lastName.</param>
        /// <param name="contactInformation">contactInformation.</param>
        /// <param name="notificationPreferences">notificationPreferences.</param>
        /// <param name="mandatory">mandatory.</param>
        /// <param name="customMessageVariables">customMessageVariables.</param>
        public DistributionProfile(string tenantId = default, string userId = default, string externalId = default, string firstName = default, string lastName = default, ContactInformation contactInformation = default, NotificationPreferences notificationPreferences = default, bool mandatory = default, Dictionary<string, string> customMessageVariables = default)
        {
            this.TenantId = tenantId;
            this.UserId = userId;
            this.ExternalId = externalId;
            this.FirstName = firstName;
            this.LastName = lastName;
            this.ContactInformation = contactInformation;
            this.NotificationPreferences = notificationPreferences;
            this.Mandatory = mandatory;
            this.CustomMessageVariables = customMessageVariables;
        }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [DataMember(Name = "tenantId", EmitDefaultValue = false)]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [DataMember(Name = "externalId", EmitDefaultValue = false)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [DataMember(Name = "firstName", EmitDefaultValue = false)]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [DataMember(Name = "lastName", EmitDefaultValue = false)]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets ContactInformation
        /// </summary>
        [DataMember(Name = "contactInformation", EmitDefaultValue = false)]
        public ContactInformation ContactInformation { get; set; }

        /// <summary>
        /// Gets or Sets NotificationPreferences
        /// </summary>
        [DataMember(Name = "notificationPreferences", EmitDefaultValue = false)]
        public NotificationPreferences NotificationPreferences { get; set; }

        /// <summary>
        /// Gets or Sets Mandatory
        /// </summary>
        [DataMember(Name = "mandatory", EmitDefaultValue = true)]
        public bool Mandatory { get; set; }

        /// <summary>
        /// Gets or Sets CustomMessageVariables
        /// </summary>
        [DataMember(Name = "customMessageVariables", EmitDefaultValue = false)]
        public Dictionary<string, string> CustomMessageVariables { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DistributionProfile {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  ContactInformation: ").Append(ContactInformation).Append("\n");
            sb.Append("  NotificationPreferences: ").Append(NotificationPreferences).Append("\n");
            sb.Append("  Mandatory: ").Append(Mandatory).Append("\n");
            sb.Append("  CustomMessageVariables: ").Append(CustomMessageVariables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
