/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// Feature
    /// </summary>
    [DataContract(Name = "Feature")]
    public partial class Feature : IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Point for value: Point
            /// </summary>
            [EnumMember(Value = "Point")]
            Point = 1,

            /// <summary>
            /// Enum MultiPoint for value: MultiPoint
            /// </summary>
            [EnumMember(Value = "MultiPoint")]
            MultiPoint = 2,

            /// <summary>
            /// Enum LineString for value: LineString
            /// </summary>
            [EnumMember(Value = "LineString")]
            LineString = 3,

            /// <summary>
            /// Enum MultiLineString for value: MultiLineString
            /// </summary>
            [EnumMember(Value = "MultiLineString")]
            MultiLineString = 4,

            /// <summary>
            /// Enum Polygon for value: Polygon
            /// </summary>
            [EnumMember(Value = "Polygon")]
            Polygon = 5,

            /// <summary>
            /// Enum MultiPolygon for value: MultiPolygon
            /// </summary>
            [EnumMember(Value = "MultiPolygon")]
            MultiPolygon = 6,

            /// <summary>
            /// Enum GeometryCollection for value: GeometryCollection
            /// </summary>
            [EnumMember(Value = "GeometryCollection")]
            GeometryCollection = 7,

            /// <summary>
            /// Enum Feature for value: Feature
            /// </summary>
            [EnumMember(Value = "Feature")]
            Feature = 8,

            /// <summary>
            /// Enum FeatureCollection for value: FeatureCollection
            /// </summary>
            [EnumMember(Value = "FeatureCollection")]
            FeatureCollection = 9
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Feature" /> class.
        /// </summary>
        /// <param name="geometry">geometry.</param>
        /// <param name="id">id.</param>
        /// <param name="properties">properties.</param>
        /// <param name="bbox">bbox.</param>
        /// <param name="crs">crs.</param>
        /// <param name="type">type.</param>
        public Feature(IGeometryObject geometry = default, string id = default, Dictionary<string, Object> properties = default, List<double> bbox = default, IcrsObject crs = default, TypeEnum? type = default)
        {
            this.Geometry = geometry;
            this.Id = id;
            this.Properties = properties;
            this.Bbox = bbox;
            this.Crs = crs;
            this.Type = type;
        }

        /// <summary>
        /// Gets or Sets Geometry
        /// </summary>
        [DataMember(Name = "geometry", EmitDefaultValue = false)]
        public IGeometryObject Geometry { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [DataMember(Name = "properties", EmitDefaultValue = false)]
        public Dictionary<string, Object> Properties { get; set; }

        /// <summary>
        /// Gets or Sets Bbox
        /// </summary>
        [DataMember(Name = "bbox", EmitDefaultValue = false)]
        public List<double> Bbox { get; set; }

        /// <summary>
        /// Gets or Sets Crs
        /// </summary>
        [DataMember(Name = "crs", EmitDefaultValue = false)]
        public IcrsObject Crs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Feature {\n");
            sb.Append("  Geometry: ").Append(Geometry).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  Bbox: ").Append(Bbox).Append("\n");
            sb.Append("  Crs: ").Append(Crs).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
