/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// Defines FormType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FormType
    {
        /// <summary>
        /// Enum Unused for value: Unused
        /// </summary>
        [EnumMember(Value = "Unused")]
        Unused = 1,

        /// <summary>
        /// Enum Eas for value: Eas
        /// </summary>
        [EnumMember(Value = "Eas")]
        Eas = 2,

        /// <summary>
        /// Enum Quick for value: Quick
        /// </summary>
        [EnumMember(Value = "Quick")]
        Quick = 3,

        /// <summary>
        /// Enum Public for value: Public
        /// </summary>
        [EnumMember(Value = "Public")]
        Public = 4,

        /// <summary>
        /// Enum Balsa for value: Balsa
        /// </summary>
        [EnumMember(Value = "Balsa")]
        Balsa = 5,

        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown = 6
    }

}
