/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// IncidentSettings
    /// </summary>
    [DataContract(Name = "IncidentSettings")]
    public partial class IncidentSettings : IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Generic for value: Generic
            /// </summary>
            [EnumMember(Value = "Generic")]
            Generic = 1,

            /// <summary>
            /// Enum Named for value: Named
            /// </summary>
            [EnumMember(Value = "Named")]
            Named = 2,

            /// <summary>
            /// Enum NotSpecified for value: NotSpecified
            /// </summary>
            [EnumMember(Value = "NotSpecified")]
            NotSpecified = 3
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [DataMember(Name = "priority", EmitDefaultValue = false)]
        public PriorityType? Priority { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="IncidentSettings" /> class.
        /// </summary>
        /// <param name="id">Type: Guid. Identifier for this incident..</param>
        /// <param name="name">name.</param>
        /// <param name="type">type.</param>
        /// <param name="priority">priority.</param>
        /// <param name="externalId">externalId.</param>
        public IncidentSettings(string id = default, string name = default, TypeEnum? type = default, PriorityType? priority = default, string externalId = default)
        {
            this.Id = id;
            this.Name = name;
            this.Type = type;
            this.Priority = priority;
            this.ExternalId = externalId;
        }

        /// <summary>
        /// Type: Guid. Identifier for this incident.
        /// </summary>
        /// <value>Type: Guid. Identifier for this incident.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [DataMember(Name = "externalId", EmitDefaultValue = false)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IncidentSettings {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
