/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// IncidentEvent
    /// </summary>
    [DataContract(Name = "IncidentEvent")]
    public partial class IncidentEvent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IncidentEvent" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="incidentCategory">incidentCategory.</param>
        /// <param name="incidentType">incidentType.</param>
        /// <param name="largeScaleEventId">largeScaleEventId.</param>
        public IncidentEvent(string id = default, string name = default, IncidentCategory incidentCategory = default, IncidentType incidentType = default, string largeScaleEventId = default)
        {
            this.Id = id;
            this.Name = name;
            this.IncidentCategory = incidentCategory;
            this.IncidentType = incidentType;
            this.LargeScaleEventId = largeScaleEventId;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets IncidentCategory
        /// </summary>
        [DataMember(Name = "incidentCategory", EmitDefaultValue = false)]
        public IncidentCategory IncidentCategory { get; set; }

        /// <summary>
        /// Gets or Sets IncidentType
        /// </summary>
        [DataMember(Name = "incidentType", EmitDefaultValue = false)]
        public IncidentType IncidentType { get; set; }

        /// <summary>
        /// Gets or Sets LargeScaleEventId
        /// </summary>
        [DataMember(Name = "largeScaleEventId", EmitDefaultValue = false)]
        public string LargeScaleEventId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IncidentEvent {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IncidentCategory: ").Append(IncidentCategory).Append("\n");
            sb.Append("  IncidentType: ").Append(IncidentType).Append("\n");
            sb.Append("  LargeScaleEventId: ").Append(LargeScaleEventId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
