/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// MessageSettings
    /// </summary>
    [DataContract(Name = "MessageSettings")]
    public partial class MessageSettings : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [DataMember(Name = "priority", EmitDefaultValue = false)]
        public PriorityType? Priority { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MessageSettings" /> class.
        /// </summary>
        /// <param name="basic">basic.</param>
        /// <param name="conference">conference.</param>
        /// <param name="files">files.</param>
        /// <param name="language">language.</param>
        /// <param name="translate">translate.</param>
        /// <param name="poll">poll.</param>
        /// <param name="priority">priority.</param>
        /// <param name="incidentId">incidentId.</param>
        /// <param name="incidentEvent">incidentEvent.</param>
        /// <param name="incident">incident.</param>
        /// <param name="severityAssessment">severityAssessment.</param>
        /// <param name="survey">survey.</param>
        /// <param name="socialMedia">socialMedia.</param>
        /// <param name="content">content.</param>
        /// <param name="expireDateTimeUtc">expireDateTimeUtc.</param>
        /// <param name="customMessageVariables">customMessageVariables.</param>
        public MessageSettings(BasicMessage basic = default, ConferenceInvitation conference = default, List<FileDetails> files = default, string language = default, bool? translate = default, PollQuestionModel poll = default, PriorityType? priority = default, string incidentId = default, IncidentEvent incidentEvent = default, IncidentSettings incident = default, SeverityAssessment severityAssessment = default, SurveySettings survey = default, SocialMediaSettings socialMedia = default, ContentSettings content = default, DateTime expireDateTimeUtc = default, CustomMessageVariables customMessageVariables = default)
        {
            this.Basic = basic;
            this.Conference = conference;
            this.Files = files;
            this.Language = language;
            this.Translate = translate;
            this.Poll = poll;
            this.Priority = priority;
            this.IncidentId = incidentId;
            this.IncidentEvent = incidentEvent;
            this.Incident = incident;
            this.SeverityAssessment = severityAssessment;
            this.Survey = survey;
            this.SocialMedia = socialMedia;
            this.Content = content;
            this.ExpireDateTimeUtc = expireDateTimeUtc;
            this.CustomMessageVariables = customMessageVariables;
        }

        /// <summary>
        /// Gets or Sets Basic
        /// </summary>
        [DataMember(Name = "basic", EmitDefaultValue = false)]
        public BasicMessage Basic { get; set; }

        /// <summary>
        /// Gets or Sets Conference
        /// </summary>
        [DataMember(Name = "conference", EmitDefaultValue = false)]
        public ConferenceInvitation Conference { get; set; }

        /// <summary>
        /// Gets or Sets Files
        /// </summary>
        [DataMember(Name = "files", EmitDefaultValue = false)]
        public List<FileDetails> Files { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [DataMember(Name = "language", EmitDefaultValue = false)]
        public string Language { get; set; }

        /// <summary>
        /// Gets or Sets Translate
        /// </summary>
        [DataMember(Name = "translate", EmitDefaultValue = true)]
        public bool? Translate { get; set; }

        /// <summary>
        /// Gets or Sets Poll
        /// </summary>
        [DataMember(Name = "poll", EmitDefaultValue = false)]
        public PollQuestionModel Poll { get; set; }

        /// <summary>
        /// Gets or Sets IncidentId
        /// </summary>
        [DataMember(Name = "incidentId", EmitDefaultValue = false)]
        public string IncidentId { get; set; }

        /// <summary>
        /// Gets or Sets IncidentEvent
        /// </summary>
        [DataMember(Name = "incidentEvent", EmitDefaultValue = false)]
        public IncidentEvent IncidentEvent { get; set; }

        /// <summary>
        /// Gets or Sets Incident
        /// </summary>
        [DataMember(Name = "incident", EmitDefaultValue = false)]
        public IncidentSettings Incident { get; set; }

        /// <summary>
        /// Gets or Sets SeverityAssessment
        /// </summary>
        [DataMember(Name = "severityAssessment", EmitDefaultValue = false)]
        public SeverityAssessment SeverityAssessment { get; set; }

        /// <summary>
        /// Gets or Sets Survey
        /// </summary>
        [DataMember(Name = "survey", EmitDefaultValue = false)]
        public SurveySettings Survey { get; set; }

        /// <summary>
        /// Gets or Sets SocialMedia
        /// </summary>
        [DataMember(Name = "socialMedia", EmitDefaultValue = false)]
        public SocialMediaSettings SocialMedia { get; set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [DataMember(Name = "content", EmitDefaultValue = false)]
        public ContentSettings Content { get; set; }

        /// <summary>
        /// Gets or Sets ExpireDateTimeUtc
        /// </summary>
        [DataMember(Name = "expireDateTimeUtc", EmitDefaultValue = false)]
        public DateTime ExpireDateTimeUtc { get; set; }

        /// <summary>
        /// Gets or Sets CustomMessageVariables
        /// </summary>
        [DataMember(Name = "customMessageVariables", EmitDefaultValue = false)]
        public CustomMessageVariables CustomMessageVariables { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MessageSettings {\n");
            sb.Append("  Basic: ").Append(Basic).Append("\n");
            sb.Append("  Conference: ").Append(Conference).Append("\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Translate: ").Append(Translate).Append("\n");
            sb.Append("  Poll: ").Append(Poll).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  IncidentId: ").Append(IncidentId).Append("\n");
            sb.Append("  IncidentEvent: ").Append(IncidentEvent).Append("\n");
            sb.Append("  Incident: ").Append(Incident).Append("\n");
            sb.Append("  SeverityAssessment: ").Append(SeverityAssessment).Append("\n");
            sb.Append("  Survey: ").Append(Survey).Append("\n");
            sb.Append("  SocialMedia: ").Append(SocialMedia).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  ExpireDateTimeUtc: ").Append(ExpireDateTimeUtc).Append("\n");
            sb.Append("  CustomMessageVariables: ").Append(CustomMessageVariables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
