/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// MobileBroadcastChannel
    /// </summary>
    [DataContract(Name = "MobileBroadcastChannel")]
    public partial class MobileBroadcastChannel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MobileBroadcastChannel" /> class.
        /// </summary>
        /// <param name="send">send.</param>
        /// <param name="message">message.</param>
        public MobileBroadcastChannel(bool send = default, string message = default)
        {
            this.Send = send;
            this.Message = message;
        }

        /// <summary>
        /// Gets or Sets Send
        /// </summary>
        [DataMember(Name = "send", EmitDefaultValue = true)]
        public bool Send { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MobileBroadcastChannel {\n");
            sb.Append("  Send: ").Append(Send).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
