/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// NextdoorChannelStatus
    /// </summary>
    [DataContract(Name = "NextdoorChannelStatus")]
    public partial class NextdoorChannelStatus : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NextdoorChannelStatus" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="regionId">regionId.</param>
        /// <param name="alertId">alertId.</param>
        /// <param name="userId">userId.</param>
        /// <param name="accountId">accountId.</param>
        /// <param name="accountName">accountName.</param>
        /// <param name="postUrl">postUrl.</param>
        /// <param name="statusCode">statusCode.</param>
        /// <param name="isError">isError.</param>
        /// <param name="messages">messages.</param>
        /// <param name="createdDateUtc">createdDateUtc.</param>
        /// <param name="createdBy">createdBy.</param>
        public NextdoorChannelStatus(int id = default, int regionId = default, int alertId = default, int userId = default, int accountId = default, string accountName = default, string postUrl = default, string statusCode = default, bool isError = default, List<string> messages = default, DateTime createdDateUtc = default, string createdBy = default)
        {
            this.Id = id;
            this.RegionId = regionId;
            this.AlertId = alertId;
            this.UserId = userId;
            this.AccountId = accountId;
            this.AccountName = accountName;
            this.PostUrl = postUrl;
            this.StatusCode = statusCode;
            this.IsError = isError;
            this.Messages = messages;
            this.CreatedDateUtc = createdDateUtc;
            this.CreatedBy = createdBy;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets RegionId
        /// </summary>
        [DataMember(Name = "regionId", EmitDefaultValue = false)]
        public int RegionId { get; set; }

        /// <summary>
        /// Gets or Sets AlertId
        /// </summary>
        [DataMember(Name = "alertId", EmitDefaultValue = false)]
        public int AlertId { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public int UserId { get; set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", EmitDefaultValue = false)]
        public int AccountId { get; set; }

        /// <summary>
        /// Gets or Sets AccountName
        /// </summary>
        [DataMember(Name = "accountName", EmitDefaultValue = false)]
        public string AccountName { get; set; }

        /// <summary>
        /// Gets or Sets PostUrl
        /// </summary>
        [DataMember(Name = "postUrl", EmitDefaultValue = false)]
        public string PostUrl { get; set; }

        /// <summary>
        /// Gets or Sets StatusCode
        /// </summary>
        [DataMember(Name = "statusCode", EmitDefaultValue = false)]
        public string StatusCode { get; set; }

        /// <summary>
        /// Gets or Sets IsError
        /// </summary>
        [DataMember(Name = "isError", EmitDefaultValue = true)]
        public bool IsError { get; set; }

        /// <summary>
        /// Gets or Sets Messages
        /// </summary>
        [DataMember(Name = "messages", EmitDefaultValue = false)]
        public List<string> Messages { get; set; }

        /// <summary>
        /// Gets or Sets CreatedDateUtc
        /// </summary>
        [DataMember(Name = "createdDateUtc", EmitDefaultValue = false)]
        public DateTime CreatedDateUtc { get; set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [DataMember(Name = "createdBy", EmitDefaultValue = false)]
        public string CreatedBy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NextdoorChannelStatus {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  RegionId: ").Append(RegionId).Append("\n");
            sb.Append("  AlertId: ").Append(AlertId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  AccountName: ").Append(AccountName).Append("\n");
            sb.Append("  PostUrl: ").Append(PostUrl).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  IsError: ").Append(IsError).Append("\n");
            sb.Append("  Messages: ").Append(Messages).Append("\n");
            sb.Append("  CreatedDateUtc: ").Append(CreatedDateUtc).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
