/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// PhoneNumber
    /// </summary>
    [DataContract(Name = "PhoneNumber")]
    public partial class PhoneNumber : IValidatableObject
    {
        /// <summary>
        /// Defines PhoneType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PhoneTypeEnum
        {
            /// <summary>
            /// Enum Cell for value: Cell
            /// </summary>
            [EnumMember(Value = "Cell")]
            Cell = 1,

            /// <summary>
            /// Enum Business for value: Business
            /// </summary>
            [EnumMember(Value = "Business")]
            Business = 2,

            /// <summary>
            /// Enum Home for value: Home
            /// </summary>
            [EnumMember(Value = "Home")]
            Home = 3,

            /// <summary>
            /// Enum Government for value: Government
            /// </summary>
            [EnumMember(Value = "Government")]
            Government = 4,

            /// <summary>
            /// Enum Fax for value: Fax
            /// </summary>
            [EnumMember(Value = "Fax")]
            Fax = 5,

            /// <summary>
            /// Enum Pager for value: Pager
            /// </summary>
            [EnumMember(Value = "Pager")]
            Pager = 6,

            /// <summary>
            /// Enum Blackberry for value: Blackberry
            /// </summary>
            [EnumMember(Value = "Blackberry")]
            Blackberry = 7,

            /// <summary>
            /// Enum None for value: None
            /// </summary>
            [EnumMember(Value = "None")]
            None = 8
        }


        /// <summary>
        /// Gets or Sets PhoneType
        /// </summary>
        [DataMember(Name = "phoneType", EmitDefaultValue = false)]
        public PhoneTypeEnum? PhoneType { get; set; }
        /// <summary>
        /// Defines SmsStatus
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SmsStatusEnum
        {
            /// <summary>
            /// Enum Inactive for value: Inactive
            /// </summary>
            [EnumMember(Value = "Inactive")]
            Inactive = 1,

            /// <summary>
            /// Enum Unsubscribed for value: Unsubscribed
            /// </summary>
            [EnumMember(Value = "Unsubscribed")]
            Unsubscribed = 2,

            /// <summary>
            /// Enum Active for value: Active
            /// </summary>
            [EnumMember(Value = "Active")]
            Active = 3,

            /// <summary>
            /// Enum Unsupported for value: Unsupported
            /// </summary>
            [EnumMember(Value = "Unsupported")]
            Unsupported = 4,

            /// <summary>
            /// Enum UnreachablePhoneNumber for value: UnreachablePhoneNumber
            /// </summary>
            [EnumMember(Value = "UnreachablePhoneNumber")]
            UnreachablePhoneNumber = 5
        }


        /// <summary>
        /// Gets or Sets SmsStatus
        /// </summary>
        [DataMember(Name = "smsStatus", EmitDefaultValue = false)]
        public SmsStatusEnum? SmsStatus { get; set; }
        /// <summary>
        /// Defines VoiceStatus
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum VoiceStatusEnum
        {
            /// <summary>
            /// Enum Inactive for value: Inactive
            /// </summary>
            [EnumMember(Value = "Inactive")]
            Inactive = 1,

            /// <summary>
            /// Enum Unsubscribed for value: Unsubscribed
            /// </summary>
            [EnumMember(Value = "Unsubscribed")]
            Unsubscribed = 2,

            /// <summary>
            /// Enum Active for value: Active
            /// </summary>
            [EnumMember(Value = "Active")]
            Active = 3,

            /// <summary>
            /// Enum Unsupported for value: Unsupported
            /// </summary>
            [EnumMember(Value = "Unsupported")]
            Unsupported = 4,

            /// <summary>
            /// Enum UnreachablePhoneNumber for value: UnreachablePhoneNumber
            /// </summary>
            [EnumMember(Value = "UnreachablePhoneNumber")]
            UnreachablePhoneNumber = 5
        }


        /// <summary>
        /// Gets or Sets VoiceStatus
        /// </summary>
        [DataMember(Name = "voiceStatus", EmitDefaultValue = false)]
        public VoiceStatusEnum? VoiceStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PhoneNumber" /> class.
        /// </summary>
        /// <param name="number">number.</param>
        /// <param name="priority">priority.</param>
        /// <param name="phoneType">phoneType.</param>
        /// <param name="smsStatus">smsStatus.</param>
        /// <param name="smsOptOutDate">smsOptOutDate.</param>
        /// <param name="voiceStatus">voiceStatus.</param>
        /// <param name="voiceOptOutDate">voiceOptOutDate.</param>
        public PhoneNumber(string number = default, int priority = default, PhoneTypeEnum? phoneType = default, SmsStatusEnum? smsStatus = default, DateTime smsOptOutDate = default, VoiceStatusEnum? voiceStatus = default, DateTime voiceOptOutDate = default)
        {
            this.Number = number;
            this.Priority = priority;
            this.PhoneType = phoneType;
            this.SmsStatus = smsStatus;
            this.SmsOptOutDate = smsOptOutDate;
            this.VoiceStatus = voiceStatus;
            this.VoiceOptOutDate = voiceOptOutDate;
        }

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [DataMember(Name = "number", EmitDefaultValue = false)]
        public string Number { get; set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [DataMember(Name = "priority", EmitDefaultValue = false)]
        public int Priority { get; set; }

        /// <summary>
        /// Gets or Sets SmsOptOutDate
        /// </summary>
        [DataMember(Name = "smsOptOutDate", EmitDefaultValue = false)]
        public DateTime SmsOptOutDate { get; set; }

        /// <summary>
        /// Gets or Sets VoiceOptOutDate
        /// </summary>
        [DataMember(Name = "voiceOptOutDate", EmitDefaultValue = false)]
        public DateTime VoiceOptOutDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PhoneNumber {\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  PhoneType: ").Append(PhoneType).Append("\n");
            sb.Append("  SmsStatus: ").Append(SmsStatus).Append("\n");
            sb.Append("  SmsOptOutDate: ").Append(SmsOptOutDate).Append("\n");
            sb.Append("  VoiceStatus: ").Append(VoiceStatus).Append("\n");
            sb.Append("  VoiceOptOutDate: ").Append(VoiceOptOutDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
