/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// Defines ScheduleType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ScheduleType
    {
        /// <summary>
        /// Enum Hickory for value: Hickory
        /// </summary>
        [EnumMember(Value = "Hickory")]
        Hickory = 1,

        /// <summary>
        /// Enum Balsa for value: Balsa
        /// </summary>
        [EnumMember(Value = "Balsa")]
        Balsa = 2
    }

}
