/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// ShortenedUrl
    /// </summary>
    [DataContract(Name = "ShortenedUrl")]
    public partial class ShortenedUrl : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShortenedUrl" /> class.
        /// </summary>
        /// <param name="id">ID of the shortened URL.</param>
        /// <param name="varShortenedUrl">Shortened URL of the shortened URL.</param>
        /// <param name="originalUrl">Original URL of the shortened URL.</param>
        /// <param name="dateCreated">Date created of the shortened URL.</param>
        /// <param name="dateUpdated">Date updated of the shortened URL.</param>
        /// <param name="views">Number of views of the shortened URL.</param>
        /// <param name="disabled">Enabled state of the shortened URL.</param>
        public ShortenedUrl(int id = default, string varShortenedUrl = default, string originalUrl = default, DateTime dateCreated = default, DateTime dateUpdated = default, int views = default, bool disabled = default)
        {
            this.Id = id;
            this.VarShortenedUrl = varShortenedUrl;
            this.OriginalUrl = originalUrl;
            this.DateCreated = dateCreated;
            this.DateUpdated = dateUpdated;
            this.Views = views;
            this.Disabled = disabled;
        }

        /// <summary>
        /// ID of the shortened URL
        /// </summary>
        /// <value>ID of the shortened URL</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Shortened URL of the shortened URL
        /// </summary>
        /// <value>Shortened URL of the shortened URL</value>
        [DataMember(Name = "shortenedUrl", EmitDefaultValue = false)]
        public string VarShortenedUrl { get; set; }

        /// <summary>
        /// Original URL of the shortened URL
        /// </summary>
        /// <value>Original URL of the shortened URL</value>
        [DataMember(Name = "originalUrl", EmitDefaultValue = false)]
        public string OriginalUrl { get; set; }

        /// <summary>
        /// Date created of the shortened URL
        /// </summary>
        /// <value>Date created of the shortened URL</value>
        [DataMember(Name = "dateCreated", EmitDefaultValue = false)]
        public DateTime DateCreated { get; set; }

        /// <summary>
        /// Date updated of the shortened URL
        /// </summary>
        /// <value>Date updated of the shortened URL</value>
        [DataMember(Name = "dateUpdated", EmitDefaultValue = false)]
        public DateTime DateUpdated { get; set; }

        /// <summary>
        /// Number of views of the shortened URL
        /// </summary>
        /// <value>Number of views of the shortened URL</value>
        [DataMember(Name = "views", EmitDefaultValue = false)]
        public int Views { get; set; }

        /// <summary>
        /// Enabled state of the shortened URL
        /// </summary>
        /// <value>Enabled state of the shortened URL</value>
        [DataMember(Name = "disabled", EmitDefaultValue = true)]
        public bool Disabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShortenedUrl {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  VarShortenedUrl: ").Append(VarShortenedUrl).Append("\n");
            sb.Append("  OriginalUrl: ").Append(OriginalUrl).Append("\n");
            sb.Append("  DateCreated: ").Append(DateCreated).Append("\n");
            sb.Append("  DateUpdated: ").Append(DateUpdated).Append("\n");
            sb.Append("  Views: ").Append(Views).Append("\n");
            sb.Append("  Disabled: ").Append(Disabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
