/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// SurveySummary
    /// </summary>
    [DataContract(Name = "SurveySummary")]
    public partial class SurveySummary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SurveySummary" /> class.
        /// </summary>
        /// <param name="survey">survey.</param>
        /// <param name="response">response.</param>
        /// <param name="allowMultipleResponses">allowMultipleResponses.</param>
        public SurveySummary(ObjectReference survey = default, ObjectReference response = default, bool allowMultipleResponses = default)
        {
            this.Survey = survey;
            this.Response = response;
            this.AllowMultipleResponses = allowMultipleResponses;
        }

        /// <summary>
        /// Gets or Sets Survey
        /// </summary>
        [DataMember(Name = "survey", EmitDefaultValue = false)]
        public ObjectReference Survey { get; set; }

        /// <summary>
        /// Gets or Sets Response
        /// </summary>
        [DataMember(Name = "response", EmitDefaultValue = false)]
        public ObjectReference Response { get; set; }

        /// <summary>
        /// Gets or Sets AllowMultipleResponses
        /// </summary>
        [DataMember(Name = "allowMultipleResponses", EmitDefaultValue = true)]
        public bool AllowMultipleResponses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SurveySummary {\n");
            sb.Append("  Survey: ").Append(Survey).Append("\n");
            sb.Append("  Response: ").Append(Response).Append("\n");
            sb.Append("  AllowMultipleResponses: ").Append(AllowMultipleResponses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
