/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// ValidationFailure
    /// </summary>
    [DataContract(Name = "ValidationFailure")]
    public partial class ValidationFailure : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationFailure" /> class.
        /// </summary>
        /// <param name="propertyName">propertyName.</param>
        /// <param name="errorMessage">errorMessage.</param>
        /// <param name="errorCode">errorCode.</param>
        /// <param name="attemptedValue">attemptedValue.</param>
        /// <param name="resourceKey">resourceKey.</param>
        public ValidationFailure(string propertyName = default, string errorMessage = default, string errorCode = default, Object attemptedValue = default, string resourceKey = default)
        {
            this.PropertyName = propertyName;
            this.ErrorMessage = errorMessage;
            this.ErrorCode = errorCode;
            this.AttemptedValue = attemptedValue;
            this.ResourceKey = resourceKey;
        }

        /// <summary>
        /// Gets or Sets PropertyName
        /// </summary>
        [DataMember(Name = "propertyName", EmitDefaultValue = false)]
        public string PropertyName { get; set; }

        /// <summary>
        /// Gets or Sets ErrorMessage
        /// </summary>
        [DataMember(Name = "errorMessage", EmitDefaultValue = false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [DataMember(Name = "errorCode", EmitDefaultValue = false)]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Gets or Sets AttemptedValue
        /// </summary>
        [DataMember(Name = "attemptedValue", EmitDefaultValue = false)]
        public Object AttemptedValue { get; set; }

        /// <summary>
        /// Gets or Sets ResourceKey
        /// </summary>
        [DataMember(Name = "resourceKey", EmitDefaultValue = false)]
        public string ResourceKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidationFailure {\n");
            sb.Append("  PropertyName: ").Append(PropertyName).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  AttemptedValue: ").Append(AttemptedValue).Append("\n");
            sb.Append("  ResourceKey: ").Append(ResourceKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
