/*
 * Alerting
 *
 * Alerting Module API Specification
 *
 * The version of the OpenAPI document: 4.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Konexus.Alerting.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Konexus.Alerting.ApiClient.Client.OpenAPIDateConverter;

namespace Konexus.Alerting.ApiClient.Model
{
    /// <summary>
    /// VoiceChannel
    /// </summary>
    [DataContract(Name = "VoiceChannel")]
    public partial class VoiceChannel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VoiceChannel" /> class.
        /// </summary>
        /// <param name="recipientCount">recipientCount.</param>
        /// <param name="send">send.</param>
        /// <param name="homePhone">homePhone.</param>
        /// <param name="cellPhone">cellPhone.</param>
        /// <param name="businessPhone">businessPhone.</param>
        /// <param name="landLine">landLine.</param>
        /// <param name="message">message.</param>
        /// <param name="audioFile">audioFile.</param>
        /// <param name="channelMessage">channelMessage.</param>
        public VoiceChannel(int recipientCount = default, bool send = default, bool homePhone = default, bool cellPhone = default, bool businessPhone = default, bool landLine = default, string message = default, FileModel audioFile = default, string channelMessage = default)
        {
            this.RecipientCount = recipientCount;
            this.Send = send;
            this.HomePhone = homePhone;
            this.CellPhone = cellPhone;
            this.BusinessPhone = businessPhone;
            this.LandLine = landLine;
            this.Message = message;
            this.AudioFile = audioFile;
            this.ChannelMessage = channelMessage;
        }

        /// <summary>
        /// Gets or Sets RecipientCount
        /// </summary>
        [DataMember(Name = "recipientCount", EmitDefaultValue = false)]
        public int RecipientCount { get; set; }

        /// <summary>
        /// Gets or Sets Send
        /// </summary>
        [DataMember(Name = "send", EmitDefaultValue = true)]
        public bool Send { get; set; }

        /// <summary>
        /// Gets or Sets HomePhone
        /// </summary>
        [DataMember(Name = "homePhone", EmitDefaultValue = true)]
        public bool HomePhone { get; set; }

        /// <summary>
        /// Gets or Sets CellPhone
        /// </summary>
        [DataMember(Name = "cellPhone", EmitDefaultValue = true)]
        public bool CellPhone { get; set; }

        /// <summary>
        /// Gets or Sets BusinessPhone
        /// </summary>
        [DataMember(Name = "businessPhone", EmitDefaultValue = true)]
        public bool BusinessPhone { get; set; }

        /// <summary>
        /// Gets or Sets LandLine
        /// </summary>
        [DataMember(Name = "landLine", EmitDefaultValue = true)]
        public bool LandLine { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets AudioFile
        /// </summary>
        [DataMember(Name = "audioFile", EmitDefaultValue = false)]
        public FileModel AudioFile { get; set; }

        /// <summary>
        /// Gets or Sets ChannelMessage
        /// </summary>
        [DataMember(Name = "channelMessage", EmitDefaultValue = false)]
        public string ChannelMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VoiceChannel {\n");
            sb.Append("  RecipientCount: ").Append(RecipientCount).Append("\n");
            sb.Append("  Send: ").Append(Send).Append("\n");
            sb.Append("  HomePhone: ").Append(HomePhone).Append("\n");
            sb.Append("  CellPhone: ").Append(CellPhone).Append("\n");
            sb.Append("  BusinessPhone: ").Append(BusinessPhone).Append("\n");
            sb.Append("  LandLine: ").Append(LandLine).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  AudioFile: ").Append(AudioFile).Append("\n");
            sb.Append("  ChannelMessage: ").Append(ChannelMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
